import fs from "fs"; import path from "path";
const PC = process.argv[2], ROOT = path.resolve(PC, "../../.."), KEY = process.argv[3], T0 = +process.argv[4], T1 = +process.argv[5], EVERY = +(process.argv[6] || 12), SW = process.argv[7] || "R";
const { buildBodySpec } = await import(PC + "/pc_body.js"); const { loadJolt } = await import(PC + "/pc_jolt.js"); const C2 = await import(PC + "/pc_gatec2.js"); const { Q, V } = await import(PC + "/pc_math.js");
const dir = path.join(ROOT, "assets/characters/outfield/gabriel"), rig = JSON.parse(fs.readFileSync(path.join(dir, "rig.json"), "utf8")), buf = fs.readFileSync(path.join(dir, "mesh.bin"));
const ab = buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength), L = rig.mesh.layout, T = { Float32Array, Uint16Array, Uint32Array, Uint8Array };
const mesh = {}; for (const k of ["positions", "joints", "weights", "indices"]) mesh[k] = new T[L[k].elementType](ab, L[k].byteOffset, L[k].elementCount);
const spec = buildBodySpec(rig, mesh), J = await loadJolt(PC + "/vendor/jolt-physics.wasm-compat.js"), r = C2.runC2(J, spec, KEY, { keepStates: true });
const bi = (n) => spec.bodies.findIndex(b => b.name === n), ji = (n) => spec.joints.findIndex(j => j.name === n);
for (let i = 0; i < r.recs.length; i += EVERY) { const q = r.recs[i]; if (q.t < T0 || q.t > T1) continue; const f = q.feet[SW], fb = q.ctl && q.ctl.feetBal && q.ctl.feetBal[SW], st = SW === "L" ? "R" : "L", fs2 = q.feet[st];
  console.log(`t ${q.t.toFixed(3)} ${String(q.reqStage).padEnd(7)} ${f.state.padEnd(8)} ${SW} load ${f.load.toFixed(0).padStart(4)} shear ${f.shear.toFixed(0).padStart(4)} slipV ${(f.slipSpeed * 100).toFixed(1)} want ${fb ? fb.F.map(v => v.toFixed(0)).join(",") : "-"} | ${st} ${fs2.state.padEnd(6)} load ${fs2.load.toFixed(0)} | c ${q.com.map(v => v.toFixed(3))} ξ ${q.xi.map(v => v.toFixed(3))} ξref ${q.xiRef ? q.xiRef.map(v => v.toFixed(3)) : "-"} p* ${q.ctl ? q.ctl.pStar.map(v => v.toFixed(3)) : "-"} cop ${(q.copSmooth || [NaN, NaN]).map(v => v.toFixed(3))} atR ${fb ? [fb.at[0], fb.at[2]].map(v => v.toFixed(3)) : "-"} atL ${q.ctl && q.ctl.feetBal[st] ? [q.ctl.feetBal[st].at[0], q.ctl.feetBal[st].at[2]].map(v => v.toFixed(3)) : "-"} cls ${q.cls.slice(0, 8)} xiM ${(q.xiMargin * 100).toFixed(1)} reg ${(q.region || []).length} R.T ${q.feet[SW].touching ? 1 : 0} knee ${(q.jt[ji("knee_" + SW)].act * 57.3).toFixed(0)}/${(q.jt[ji("knee_" + SW)].fin * 57.3).toFixed(0)}`); }
