import fs from "fs"; import path from "path";
const PC = process.argv[2], ROOT = path.resolve(PC, "../../.."), KEY = process.argv[3], T0 = +process.argv[4], T1 = +process.argv[5], EVERY = +(process.argv[6] || 12), SW = process.argv[7] || "R";
const { buildBodySpec } = await import(PC + "/pc_body.js"); const { loadJolt } = await import(PC + "/pc_jolt.js"); const C2 = await import(PC + "/pc_gatec2.js"); const { Q, V } = await import(PC + "/pc_math.js"); const { jointState } = await import(PC + "/pc_gatea.js");
const dir = path.join(ROOT, "assets/characters/outfield/gabriel"), rig = JSON.parse(fs.readFileSync(path.join(dir, "rig.json"), "utf8")), buf = fs.readFileSync(path.join(dir, "mesh.bin"));
const ab = buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength), L = rig.mesh.layout, T = { Float32Array, Uint16Array, Uint32Array, Uint8Array };
const mesh = {}; for (const k of ["positions", "joints", "weights", "indices"]) mesh[k] = new T[L[k].elementType](ab, L[k].byteOffset, L[k].elementCount);
const spec = buildBodySpec(rig, mesh), J = await loadJolt(PC + "/vendor/jolt-physics.wasm-compat.js"), r = C2.runC2(J, spec, KEY, { keepStates: true });
const bi = (n) => spec.bodies.findIndex(b => b.name === n), ji = (n) => spec.joints.findIndex(j => j.name === n);
for (let i = 0; i < r.recs.length; i += EVERY) { const q = r.recs[i]; if (q.t < T0 || q.t > T1) continue; const p = q.states[bi("foot_" + SW)].pos, tg = q.swingTgt, pe = q.states[0].pos, pr = Q.rot(q.states[0].rot, [0, 0, 1]);
  const kn = ji("knee_" + SW), hp = ji("hip_" + SW); const e = q.jt[kn];
  console.log(`t ${q.t.toFixed(3)} ${String(q.reqStage).padEnd(7)} u ${tg ? tg.u.toFixed(2) : "-"} foot ${p.map(v => v.toFixed(3))} tgt ${tg ? tg.pos.map(v => v.toFixed(3)) : "-"} err ${tg ? V.sub(p, tg.pos).map(v => (v * 100).toFixed(1)).join(",") : "-"} cm | pelvis ${pe.map(v => v.toFixed(3))} fwd ${pr.map(v => v.toFixed(2))} | knee fin ${(e.fin * 57.3).toFixed(0)} act ${(e.act * 57.3).toFixed(0)} | hip fin−act ${(() => { const h = q.jt[hp]; let d = Q.mul(Q.conj(h.act), h.fin); if (d[3] < 0) d = d.map(x => -x); return [d[0], d[1], d[2]].map(x => (2 * x * 57.3).toFixed(1)).join(","); })()} nom−act ${(() => { const h = q.jt[hp]; let d = Q.mul(Q.conj(h.act), h.nom); if (d[3] < 0) d = d.map(x => -x); return [d[0], d[1], d[2]].map(x => (2 * x * 57.3).toFixed(1)).join(","); })()} g ${q.jt[hp].g.map(x => (x * 57.3).toFixed(1))}`); }
