import { J, body, G2 } from "./lib.mjs"; import fs from "fs";
const JDM = "/Users/zainrahman/Downloads/FC Simulator worktrees/physical-character-v1/review_artifacts/physical_character_v1/g2_walker/json/";
const withModels = (c) => c.modelsPrefix ? { ...c, models: Object.fromEntries([0, 0.1, 0.15, 0.2, 0.25].map(t => [t, JSON.parse(fs.readFileSync(JDM + c.modelsPrefix + t + ".json", "utf8"))])) } : c;
const B = { kind: "U", vd: 0.5, from: 1, ramp: { a: 0.3 }, place: "maps", uRefSim: false, lat: { rho: 0.4 }, adapt: null, reachIter: false, modelsPrefix: "mU1_tau" };
const ctrl = { ...B, ...JSON.parse(process.argv[2] || "{}") }, first = process.argv[3] || "R", at = +(process.argv[4] || 0.5), n = 12, which = (process.argv[5] || "4,5,6").split(",").map(Number);
const { spec, poses } = body("F0"), steps = Array.from({ length: n }, (_, i) => ({ sw: (i % 2 === 0) === (first === "R") ? "R" : "L", ...(i === 0 ? { fwdK: 0.7 } : i === 1 ? { fwdK: 0.9 } : {}) }));
let LOCO = null; const base = G2.TESTS_G2W.G2W_A8.loco.rhythm.walk, REF = new Map();
const r = G2.runG2a(J, spec, "G2W_A8", { poses, keepStates: true, seconds: 1.6 + n * 0.6, rhythmOver: { steps, at, walk: { swingBase: { w: "model", learn: { rate: 0.05 }, pure: [0] }, ctrl: withModels({ ...base.ctrl, ...ctrl }) } }, onLoco: l => { LOCO = l; const f = l.planner.update.bind(l.planner); l.planner.update = (...a) => { const out = f(...a); if (out && out.xiRef) REF.set(l.nStep, { xiRef: out.xiRef.slice(), kXi: out.kXi ? JSON.parse(JSON.stringify(out.kXi)) : null }); return out; }; } });
const P = LOCO.planner, D = P.exec.done.filter(d => d.kind === "rhythmic"), h0 = P.rhythm.wk.h0, hd = [Math.sin(h0), Math.cos(h0)], tF = (r.recs.find(q => q.com[1] < 0.75) || { t: 1e9 }).t;
console.log(JSON.stringify(r.recs[1000].copSmooth), JSON.stringify(r.recs[1000].xiRefP), JSON.stringify(r.recs[1000].vRef), JSON.stringify(r.recs[1000].grf).slice(0,200));
for (const k of which) { const d = D.find(e => e.stepIndex === k); if (!d) continue; const ps = d.pSt, rel = (p) => (p[0] - ps[0]) * hd[0] + (p[1] - ps[1]) * hd[1];
  console.log(`step ${k} ${d.sw} tSw0 ${d.tSw0.toFixed(2)} lift ${d.liftoff ? (d.liftoff.t - d.tSw0).toFixed(3) : "-"} td ${d.td ? (d.td.t - d.tSw0).toFixed(3) : "-"} | τ  ξ  ξref  CoP(meas)  COM  vCOM  stance-sole[min,max]`);
  for (const q of r.recs) { if (q.t < d.tSw0 || q.t > (d.td ? d.td.t : d.tSw0 + 0.5) || q.n % 12) continue; const st = d.sw === "R" ? "L" : "R", F = q.feet[st], sole = F.sole && F.sole.length ? F.sole.map(p => rel([p[0], p[2]])) : null, rf = REF.get(q.n);
    const cs = q.copSmooth, cop = cs ? rel(cs.length === 3 ? [cs[0], cs[2]] : cs) : null, xr = q.xiRefP ? rel(q.xiRefP.length === 3 ? [q.xiRefP[0], q.xiRefP[2]] : q.xiRefP) : null, vr = q.vRef ? (Array.isArray(q.vRef) ? (q.vRef.length === 3 ? q.vRef[0] * hd[0] + q.vRef[2] * hd[1] : q.vRef[0] * hd[0] + q.vRef[1] * hd[1]) : q.vRef) : null;
    console.log(`  ${(q.t - d.tSw0).toFixed(3)} ${rel(q.xi).toFixed(3)} ${xr != null ? xr.toFixed(3) : '-'} vRef ${vr != null && vr.toFixed ? vr.toFixed(2) : JSON.stringify(q.vRef)} ${cop != null ? cop.toFixed(3) : "-"} ${rel([q.com[0], q.com[2]]).toFixed(3)} ${(q.vcom[0] * hd[0] + q.vcom[2] * hd[1]).toFixed(2)} ${sole ? "[" + Math.min(...sole).toFixed(2) + "," + Math.max(...sole).toFixed(2) + "]" : "-"} load ${(F.load / 9.81 / 75).toFixed(2)}`); } }
