import { J, body, G2 } from "./lib.mjs"; import fs from "fs";
const JDM = "/Users/zainrahman/Downloads/FC Simulator worktrees/physical-character-v1/review_artifacts/physical_character_v1/g2_walker/json/";
const withModels = (c) => c.modelsPrefix ? { ...c, models: Object.fromEntries([0, 0.1, 0.15, 0.2, 0.25].map(t => [t, JSON.parse(fs.readFileSync(JDM + c.modelsPrefix + t + ".json", "utf8"))])) } : c;
const B = { kind: "U", vd: 0.5, from: 1, ramp: { a: 0.3 }, place: "maps", uRefSim: false, lat: { rho: 0.4 }, adapt: null, reachIter: false, modelsPrefix: "mU1_tau" };
const ctrl = { ...B, ...JSON.parse(process.argv[2] || "{}") }, first = process.argv[3] || "R", at = +(process.argv[4] || 0.5), n = 16;
const { spec, poses } = body("F0"), steps = Array.from({ length: n }, (_, i) => ({ sw: (i % 2 === 0) === (first === "R") ? "R" : "L", ...(i === 0 ? { fwdK: 0.7 } : i === 1 ? { fwdK: 0.9 } : {}) }));
let LOCO = null; const base = G2.TESTS_G2W.G2W_A8.loco.rhythm.walk, LL = {};
const r = G2.runG2a(J, spec, "G2W_A8", { poses, keepStates: true, seconds: 1.6 + n * 0.6, rhythmOver: { steps, at, walk: { swingBase: { w: "model", learn: { rate: 0.05 }, pure: [0] }, ctrl: withModels({ ...base.ctrl, ...ctrl }) } }, onLoco: l => { LOCO = l; const f = l.planner.exec.update.bind(l.planner.exec); l.planner.exec.update = (o, tr) => { const R = l.planner.exec.R; const out = f(o, tr); if (R && R.walkK && R.walkK.ctrlU && R.walkK.ctrlU.lateLog && !LL[R.stepIndex]) LL[R.stepIndex] = R.walkK.ctrlU.lateLog; return out; }; } });
const P = LOCO.planner, tF = (r.recs.find(q => q.com[1] < 0.75) || { t: 1e9 }).t, D = P.exec.done.filter(d => d.kind === "rhythmic"), h0 = P.rhythm.wk.h0, hd = [Math.sin(h0), Math.cos(h0)];
const U = P._uni; console.log("fall", tF.toFixed(2));
for (const lg of U.stepLog) { const d = D.find(e => e.stepIndex === lg.i); const ach = d && d.td ? (d.td.center[0] - d.pSt[0]) * hd[0] + (d.td.center[1] - d.pSt[1]) * hd[1] : null; const L = LL[lg.i]; const d0 = lg.dec[0];
  console.log(`step ${lg.i} ${lg.sw} vBar ${lg.vBar != null ? lg.vBar.toFixed(2) : "-"} | start x ${d0.x.map(v => v.toFixed(3))} u ${d0.u.toFixed(3)} T ${d0.T.toFixed(2)} pred ${(d0.mapPred || []).map(v => v.toFixed(3))}` + (L ? ` | late τ ${L.tau.toFixed(3)} x ${lg.dec[lg.dec.length - 1].x.map(v => v.toFixed(3))} eff ${L.effective.map(v => v.toFixed(3))} req ${L.req.map(v => v.toFixed(3))} pred ${(L.pred || []).map(v => v.toFixed(3))}` : "") + ` | ach ${ach != null ? ach.toFixed(3) : "-"} uAt ${d && d.td ? d.td.uAt.toFixed(2) : "-"}${d && d.td && d.td.t > tF ? " (after fall)" : ""}`); }
