import fs from "fs"; import path from "path";
const PC = process.argv[2], ROOT = path.resolve(PC, "../../.."), TEST = process.argv[3], EXTRA = JSON.parse(process.argv[4] || "{}");
const { buildBodySpec } = await import(PC + "/pc_body.js"); const { loadJolt } = await import(PC + "/pc_jolt.js"); const C1 = await import(PC + "/pc_gatec1.js"); const B = await import(PC + "/pc_balance.js"); const { jointState } = await import(PC + "/pc_gatea.js");
const dir = path.join(ROOT, "assets/characters/outfield/gabriel"), rig = JSON.parse(fs.readFileSync(path.join(dir, "rig.json"), "utf8")), buf = fs.readFileSync(path.join(dir, "mesh.bin"));
const ab = buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength), L = rig.mesh.layout, T = { Float32Array, Uint16Array, Uint32Array, Uint8Array };
const mesh = {}; for (const k of ["positions", "joints", "weights", "indices"]) mesh[k] = new T[L[k].elementType](ab, L[k].byteOffset, L[k].elementCount);
const spec = buildBodySpec(rig, mesh, { calib: "V1.1" }), J = await loadJolt(PC + "/vendor/jolt-physics.wasm-compat.js"), ji = (n) => spec.joints.findIndex(j => j.name === n);
const orig = B.BalanceController.prototype.update, log = []; B.BalanceController.prototype.update = function (o) { const u = orig.call(this, o); log.push({ t: o.t, arms: u.debug && u.debug.arms, r: u.debug && u.debug.r, tt: u.debug && u.debug.tauTrunk, cls: this.cls.state }); return u; };
const r = C1.runC1(J, spec, TEST, { keepStates: true, ctrlExtra: { reactiveArms: true, ...EXTRA } });
for (let i = 0; i < r.recs.length; i += 12) { const q = r.recs[i], lg = log[i]; if (q.t < 0.95 || q.t > 2.2) continue; const sL = jointState(spec.joints[ji("shoulder_L")], q.states), sR = jointState(spec.joints[ji("shoulder_R")], q.states), d = 57.3;
  console.log(`t ${q.t.toFixed(2)} ${q.cls.slice(0, 14).padEnd(14)} r ${lg && lg.r ? lg.r.map(v => (v * 100).toFixed(1)).join(",") : "-"} tauTrunk ${lg && lg.tt ? Math.hypot(...lg.tt).toFixed(0) : "-"} arms L ${lg && lg.arms && lg.arms.L ? `${lg.arms.L.y.toFixed(1)},${lg.arms.L.z.toFixed(1)}` : "-"} R ${lg && lg.arms && lg.arms.R ? `${lg.arms.R.y.toFixed(1)},${lg.arms.R.z.toFixed(1)}` : "-"} | shoulder L Y ${(sL.swingY * d).toFixed(0)} Z ${(sL.swingZ * d).toFixed(0)} R Y ${(sR.swingY * d).toFixed(0)} Z ${(sR.swingZ * d).toFixed(0)} | trunk ${q.trunk.toFixed(1)} ξm ${(q.xiMargin * 100).toFixed(1)} shEff L ${q.J[ji("shoulder_L")].eff.toFixed(2)}`); }
