// ═══ physchar2/tools/g3_earlier.mjs — earlier-gate re-validation record after the approved plant change (G3 criteria v2 row P2) ═══════════════
// Writes g2/json/g2_regression.json (G2 row R inputs, stated literally: G1 hashes vs the accepted baseline) and g3/json/g3_earlier.json (P2):
// G0 pass (incl. 0.9n), G1 criteria PASS on the full run, G1 browser = Node, G2 criteria rows (row R superseded by the approved change), G2 browser.
// usage: node tools/g3_earlier.mjs <g0_results.json> [--g2checks]   (run once before and once after g2_report_tables when G2 changes)
import fs from "fs"; import path from "path"; import zlib from "zlib"; import { fileURLToPath } from "url";
const here = path.dirname(fileURLToPath(import.meta.url)), R = path.resolve(here, "../../../../review_artifacts/physical_character_v2"), rd = (f) => JSON.parse(f.endsWith(".gz") ? zlib.gunzipSync(fs.readFileSync(f)) : fs.readFileSync(f));
// g1a = the accepted BOX-turf G1 (post-D1G1); the flat-plane decision (2026-10-03) changed the turf, so every G1 hash differs by design
const g0 = rd(process.argv[2]), g1 = rd(path.join(R, "g1/json/g1_results.json")), g1a = rd(path.join(R, "box_turf_history/g1/g1_results.json.gz")), g1b = rd(path.join(R, "g1/json/g1_browser.json"));
const hashes = (r) => { const o = {}; const walk = (x, p) => { if (Array.isArray(x)) x.forEach((y, i) => walk(y, p + "[" + (y && y.key ? y.key + "|" + (y.human || "") + "|" + (y.cfg ? JSON.stringify(y.cfg.hz) : "") : i) + "]")); else if (x && typeof x === "object") for (const [k, v] of Object.entries(x)) { if (k === "hash" && typeof v === "string") o[p] = v; else walk(v, p + "." + k); } }; walk(r, ""); return o; };
const ha = hashes(g1a), hb = hashes(g1), diff = Object.keys(ha).filter(k => ha[k] !== hb[k]), cur = ["upright", "leanF", "leanL", "singleLeg", "drop1m", "sideFirst", "awkward", "flatSupine", "impact15", "isoSelfCol"], runA = (r, k) => (r.runs || []).find(x => x.human === "V2-REF" && x.key === k);
const reg = { g0: g0.allPass === true, g0Checks: g0.global ? Object.keys(g0.global).length : null, g1curated: cur.every(k => runA(g1a, k) && runA(g1, k) && runA(g1a, k).hash === runA(g1, k).hash), g1full: diff.length === 0, g1HashesCompared: Object.keys(ha).length, g1HashDiffs: diff.slice(0, 20), g1HashDiffCount: diff.length,
  g1AllPassCommitted: g1a.allPass ?? null, g1AllPassNew: g1.allPass ?? null, note: "Compared with the ACCEPTED box-turf G1 (post-D1G1, box_turf_history/g1); every difference is the approved plant change of the flat-plane decision (2026-10-03: turf = Jolt PlaneShape; G1 reopened and revalidated under criteria v4). G2 row R ('G1 unchanged') is superseded by that approved change; the replacement is G1 criteria v4 PASS + browser = Node (G3 criteria v2 row P2)." };
fs.writeFileSync(path.join(R, "g2/json/g2_regression.json"), JSON.stringify(reg, null, 1));
let g2 = null, g2b = null; try { g2 = rd(path.join(R, "g2/json/g2_checks.json")); g2b = rd(path.join(R, "g2/json/g2_browser.json")); } catch (e) {}
const g2rows = g2 ? g2.checks.filter(c => c.id !== "R") : [], g2ok = g2 && g2rows.every(c => c.pass);
const out = { g0: g0.allPass === true, g1Pass: g1.allPass === true, g1Detail: `${g1.allPass ? "0 failing gate checks" : "FAILING"}; ${diff.length}/${Object.keys(ha).length} hashes changed vs accepted`, g1Browser: !!(g1b && g1b.allPass),
  g2Pass: !!g2ok, g2Detail: g2 ? `${g2rows.filter(c => c.pass).length}/${g2rows.length} rows pass excluding R (R literal: ${g2.checks.find(c => c.id === "R").pass ? "pass" : "superseded — G1 hashes changed by the approved plant change"})` : "not evaluated", g2Browser: !!(g2b && g2b.allPass) };
fs.writeFileSync(path.join(R, "g3/json/g3_earlier.json"), JSON.stringify(out, null, 1)); console.log(JSON.stringify(out, null, 1));
// G3 v1 row P input (historical criteria; literal "unchanged" test): the G2 part compares the current G2 run with the accepted post-D1G1 box-turf G2
try { const ga = rd(path.join(R, "g2/postD1G1/g2_results_postD1G1.json.gz")), gb = rd(path.join(R, "g2/json/g2_results.json")), k = (j) => JSON.stringify([j.group, j.human, j.sc, j.eval || null, j.rep ?? null]), m = new Map(ga.jobs.map(j => [k(j), j]));
  const hj = (j) => (j.res ? j.res.hash : j.hashA), P = gb.jobs.map(j => [m.get(k(j)), j]).filter(([a]) => a), same = P.filter(([a, b]) => hj(a) === hj(b)).length, sameOut = P.filter(([a, b]) => (a.res ? a.res.outcome : a.exact) === (b.res ? b.res.outcome : b.exact)).length;
  fs.writeFileSync(path.join(R, "g3/json/g3_regression.json"), JSON.stringify({ ...reg, g2: { n: P.length, same, committedJobs: ga.jobs.length, outcomesSame: sameOut, note: "Baseline = the accepted post-D1G1 box-turf G2. Hashes differ by the approved flat-plane turf change (G3 v1 row P is superseded; criteria v2 row P2 replaces it); outcomes compared separately." } }, null, 1)); } catch (e) { console.error("g3_regression.json not written: " + e.message); }
