// ═══ physchar2/tools/loco_probe_report.mjs — DIAGNOSTIC: tables from tools/loco_probe.mjs outputs (no simulation). usage: node tools/loco_probe_report.mjs <dir> > report.txt
import fs from "fs"; import path from "path"; import zlib from "zlib";
const dir = process.argv[2], files = fs.readdirSync(dir).filter(f => f.endsWith(".json.gz")).sort();
const runs = files.map(f => ({ f, d: JSON.parse(zlib.gunzipSync(fs.readFileSync(path.join(dir, f))).toString()) }));
const f2 = (x, n = 2) => (x == null ? "—" : typeof x === "number" ? x.toFixed(n) : String(x));
console.log("# runs (DIAGNOSTIC — not qualification)\n");
console.log("| run | kind | body | first | steps DONE | first failure (step, phase) | end s | hash |"); console.log("|---|---|---|---|---|---|---|---|");
for (const { f, d } of runs) console.log(`| ${f} | ${d.run.kind || "forward"} | ${d.run.human} | ${d.run.first} | ${d.completed} / ${d.run.steps} | ${d.fail ? `step ${d.fail.step}, ${d.fail.phase}: ${d.fail.why}` : "none"} | ${d.endT} | ${d.hashEnd} |`);
console.log("\n# per completed step\n");
const H = ["run", "step", "swing", "lift delay s", "φ contact", "clr min (φ 0.2–0.8) mm", "apex mm", "swing track max mm", "TD v down / horiz m/s", "foothold err mm", "step len mm", "stance slip mm", "stance tilt°", "ξ SS margin mm", "ξ support margin mm", "p* outside mm", "CoP outside mm", "pelvis tilt max°", "leg hard margin°", "sat axis-ticks", "Δτ0 max N·m", "E+ J", "E max/tick J", "done ξ err mm", "done |v| m/s", "re-plans", "liftoff re-cert"];
console.log("| " + H.join(" | ") + " |"); console.log("|" + H.map(() => "---").join("|") + "|");
for (const { f, d } of runs) for (const s of d.steps) { const r = s.result; if (!r) continue; const q = s.seq || {};
  console.log(`| ${f.replace(".json.gz", "")} | ${s.k} | ${s.swing} | ${f2(r.liftDelay, 3)} | ${f2(r.phiContact, 3)} | ${f2(r.clearanceMinWinMm)} | ${f2(r.apexMm, 1)} | ${f2(r.swingTrackMaxMm)} | ${r.tdVel ? f2(r.tdVel.down, 3) + " / " + f2(r.tdVel.horiz, 3) : "—"} | ${f2(r.finalPosErrMm)} | ${f2(r.stepLenMm, 1)} | ${f2(r.stanceSlipMm)} | ${f2(r.stanceTiltMaxDeg)} | ${f2(r.xiStanceMarginMinSSmm, 1)} | ${f2(r.xiSupportMarginMinMm, 1)} | ${f2(r.pStarOutsideMaxMm, 1)} | ${f2(r.copOutsideMaxMm, 1)} | ${f2(r.pelvisTiltMaxDeg)} | ${f2(r.legHardMarginMinDeg)} | ${r.satAxisTicks} | ${f2(r.dTau0MaxNm, 1)} | ${f2(r.energyClosurePosJ, 4)} | ${f2(r.energyClosureMaxTickJ, 4)} | ${f2(r.doneXiErrMm, 1)} | ${f2(r.doneComV, 3)} | ${q.replans ?? "—"} | ${q.liftoffRecert || "—"} |`); }
console.log("\n# state handed to each commanded step (the decision tick)\n");
console.log("| run | step | verdict | dx / dy m | T s | slack s | swing rel. stance (fwd, lat) m | ξ rel. stance (fwd, lat) m | ξ stance margin mm | |v_COM| m/s | pelvis yaw rel. stance° | feet yaw diff° | pelvis tilt° | stance share |"); console.log("|---|---|---|---|---|---|---|---|---|---|---|---|---|---|");
for (const { f, d } of runs) for (const s of d.steps) { const c = s.cmd; if (!c) continue; const i = c.init;
  console.log(`| ${f.replace(".json.gz", "")} | ${s.k} | ${c.verdict} | ${f2(c.dx, 3)} / ${f2(c.dy, 3)} | ${f2(c.T)} | ${f2(c.slack, 3)} | ${i.swingRelStance.map(x => f2(x, 3)).join(", ")} | ${i.xiRelStance.map(x => f2(x, 3)).join(", ")} | ${f2(i.xiStanceMarginMm, 1)} | ${f2(i.comV, 3)} | ${f2(i.pelvisYawRelStance)} | ${f2(i.feetYawDiff)} | ${f2(i.pelvisTilt)} | ${f2(i.stanceShare, 3)} |`); }
console.log("\n# load-split geometry at the first failure (the controller's G3 share rule: p* projected on the line between the feet's region centroids)\n");
console.log("| run | stance centroid (x, z) m | ξ_ref (x, z) m | p* (x, z) m | projected stance share (p*) | commanded share (stance, other) | measured Fz / BW (L, R) |"); console.log("|---|---|---|---|---|---|---|");
for (const { f, d } of runs) { const g = d.fail && d.fail.split; if (!g) continue; const st = d.steps[d.fail.step - 1], sL = st && st.stance === "L", c = sL ? g.centroidL : g.centroidR, sh = sL ? g.projLeftShare_pStar : 1 - g.projLeftShare_pStar, cs = sL ? g.cmdShare : [g.cmdShare[1], g.cmdShare[0]];
  console.log(`| ${f.replace(".json.gz", "")} | ${c.map(x => f2(x, 4)).join(", ")} | ${g.xiRef.map(x => f2(x, 4)).join(", ")} | ${g.pStar.map(x => f2(x, 4)).join(", ")} | ${f2(sh, 4)} | ${cs.map(x => f2(x, 4)).join(", ")} | ${g.FzBW.map(x => f2(x, 4)).join(", ")} |`); }
// CF-1 runs (run.cf set): the between-steps transfers, and the refused-decision path diagnosis
if (runs.some(r => r.d.run.cf)) {
  console.log("\n# CF-1 between-steps transfers (counterfactual)\n");
  console.log("| run | step | DCM travel m | ξ err max mm | ξ support margin min mm | p* margin to stance at share ≥ 0.85, min mm | would-abort (suspension needed) | release after s | trailing Fz / BW at decision | ξ err at decision mm |"); console.log("|---|---|---|---|---|---|---|---|---|---|");
  for (const { f, d } of runs) { if (!d.run.cf) continue; for (const s of d.steps) { const x = s.cmd ? s.cmd.init.transfer : null, t = s.transfer;
    if (x) console.log(`| ${f.replace(".json.gz", "")} | ${s.k} | ${f2(x.cf && x.cf.dist, 3)} | ${f2(x.xiErrMaxMm)} | ${f2(x.xiSupMarginMinMm, 1)} | ${f2(x.pStarStanceMarginMinAtHighShareMm)} | ${x.wouldAbort ? `yes: ${x.wouldAbort.pStarOutMm} mm at ${x.wouldAbort.t} s (${x.wouldAbort.phase})` : "no"} | ${f2(x.releaseAfterS, 3)} | ${f2(s.cmd.init.trailFz, 4)} | ${f2(s.cmd.init.xiErrNow)} |`);
    else if (t) console.log(`| ${f.replace(".json.gz", "")} | ${s.k} | ${f2(t.cf && t.cf.dist, 3)} | ${f2(t.xiErrMax * 1000)} | ${f2(t.xiMarginMin * 1000, 1)} | ${Number.isFinite(t.pStanceMinHi) ? f2(t.pStanceMinHi * 1000) : "—"} | ${t.wouldAbort ? `yes: ${t.wouldAbort.pStarOutMm} mm at ${t.wouldAbort.t} s (${t.wouldAbort.phase})` : "no"} | never released | ${f2(t.trailFzEnd, 4)} (end) | — |`); } }
  console.log("\n# refused commanded decisions: the planner's nominal swing, bounded leg IK per path sample (soft box = the planner's; hard = anatomical limits)\n");
  console.log("| run | step | goal rel. stance (lat, fwd) m | refused samples φ | soft-box excess of the hard solution (worst) | hard-limit IK max residual | hip→foot max / leg length m |"); console.log("|---|---|---|---|---|---|---|");
  for (const { f, d } of runs) for (const s of d.steps) { const p = s.pathDiag; if (!p) continue; const bad = p.samples.filter(x => x.softViolHard), w = bad.reduce((m, x) => { const v = Math.max(...Object.values(x.softViolHard).map(Math.abs)); return v > m.v ? { v, x } : m; }, { v: 0, x: null });
    console.log(`| ${f.replace(".json.gz", "")} | ${s.k} | ${p.goalRelStance.map(x => f2(x, 3)).join(", ")} | ${bad.map(x => x.phi).join(", ")} | ${w.x ? JSON.stringify(w.x.softViolHard) + " at φ " + w.x.phi : "—"} | ${Math.max(...p.samples.map(x => x.hardErr)).toExponential(1)} | ${f2(Math.max(...p.samples.map(x => x.hipToFootM)), 3)} / ${f2(p.legLen, 3)} |`); } }
// CF-2 runs: per-step accumulation (physical lifecycle flag, the state handed to each step, and the step's physical quality) — distinguishes bounded periodic from accumulating behaviour
if (runs.some(r => r.d.run.cf && /CF-2/.test(r.d.run.cf))) {
  console.log("\n# CF-2 per-step accumulation (every step of every run; L / R first are mirror images)\n");
  console.log("| run | step | swing | physical | feet sep. lat / fwd m (initial frame) | pelvis progress m | pelvis yaw drift° | ξ err at decision mm | |v_COM| mm/s | trailing Fz % BW | step len mm | foothold err mm | clr min mm | TD v↓ m/s | slip mm | ξ SS margin mm | pelvis tilt° | hard margin° | swing DF max° / margin to coupled° | swing foot tilt° | sat | Δτ0 N·m | E+ J | CF-2 servo solves |");
  console.log("|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|");
  for (const { f, d } of runs) { if (!(d.run.cf && /CF-2/.test(d.run.cf))) continue; for (const s of d.steps) { const c = s.cmd, i = c ? c.init : null, r = s.result || {};
    console.log(`| ${f.replace(".json.gz", "")} | ${s.k} | ${s.swing} | ${r.physical ? "yes" : "NO"} | ${i ? f2(i.feetSepInitialLatM, 3) + " / " + f2(i.feetSepInitialFwdM, 3) : "—"} | ${i && i.progress ? f2(Math.hypot(i.progress[0], i.progress[1]), 3) : "—"} | ${i ? f2(i.pelvisYawDrift) : "—"} | ${i ? f2(i.xiErrNow) : "—"} | ${i ? f2(i.comV * 1000, 1) : "—"} | ${i ? f2(i.trailFz * 100, 2) : "—"} | ${f2(r.stepLenMm, 1)} | ${f2(r.finalPosErrMm)} | ${f2(r.clearanceMinWinMm)} | ${r.tdVel ? f2(r.tdVel.down, 3) : "—"} | ${f2(r.stanceSlipMm)} | ${f2(r.xiStanceMarginMinSSmm, 1)} | ${f2(r.pelvisTiltMaxDeg)} | ${f2(r.legHardMarginMinDeg)} | ${f2(r.swingAnkleDfMaxDeg)} / ${f2(r.swingDfMarginToCoupledMinDeg)} | ${f2(r.swingFootTiltMaxDeg)} | ${r.satAxisTicks ?? "—"} | ${f2(r.dTau0MaxNm, 1)} | ${f2(r.energyClosurePosJ, 4)} | ${r.cf2 ? r.cf2.servoCoupledSolves : "—"} |`); } }
  console.log("\n| run | consecutive physical steps | first failure | CF-2 coupled solves (planner) | refused | DF max° | min margin to the coupled limit° |"); console.log("|---|---|---|---|---|---|---|");
  for (const { f, d } of runs) { if (!(d.run.cf && /CF-2/.test(d.run.cf))) continue; const T = d.cf2Totals || {};
    console.log(`| ${f.replace(".json.gz", "")} | ${d.physicalSteps} | ${d.fail ? `step ${d.fail.step} (${d.fail.phase}): ${d.fail.why}` : "none"} | ${T.coupledSolves} (${T.plannerSolves}) | ${T.refused} | ${f2(T.dfMaxDeg)} | ${f2(T.marginMinDeg)} |`); } }
// (run selection by the label's START: a later study's label names the earlier ones it builds on — corrected 8 Oct during CF-5: the substring match put CF-4 runs in the CF-3 summary)
// CF-3 runs: cadence summary per run (nominal level from the settling intervals; realized cycle; momentum at the transfer start and at each decision; saturation; release lag)
if (runs.some(r => r.d.run.cf && /^CF-1 \+ CF-2 \+ CF-3/.test(r.d.run.cf))) {
  console.log("\n# CF-3 cadence summary (nominal cycle C from the uniform settling scale: s = Ttr / 4, C = 0.73 + 8.5 s)\n");
  console.log("| run | nominal C s/step | Ttr / Tds / rel s | consecutive physical | realized cycle s (steps ≥ 2) | release lag s | |v_COM| at transfer start, max m/s | |v_COM| max in step m/s | |v_COM| at decision, max mm/s | sat axis-ticks per step | Δτ0 max N·m | E+ max J | ξ SS margin min mm | first failure | refused-decision prediction |");
  console.log("|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|");
  for (const { f, d } of runs) { if (!(d.run.cf && /^CF-1 \+ CF-2 \+ CF-3/.test(d.run.cf))) continue; const st = d.steps.filter(s => s.result && s.result.physical), s2 = st.slice(1), rng = (a, n = 2) => (a.length ? `${Math.min(...a).toFixed(n)} – ${Math.max(...a).toFixed(n)}` : "—");
    const C = 0.73 + 8.5 * d.run.Ttr / 4, pd = (d.steps.find(s => s.predDiag) || {}).predDiag;
    console.log(`| ${f.replace(".json.gz", "")} | ${C.toFixed(2)} | ${d.run.Ttr} / ${d.run.Tds} / ${d.run.rel} | ${d.physicalSteps} | ${rng(s2.map(s => s.result.durStep))} | ${rng(s2.map(s => s.cmd.init.transfer.releaseAfterS))} | ${s2.length ? Math.max(...s2.map(s => (s.transfer.start || {}).comV || 0)).toFixed(3) : "—"} | ${st.length ? Math.max(...st.map(s => s.result.comVMax)).toFixed(3) : "—"} | ${st.length ? (Math.max(...st.map(s => s.cmd.init.comV)) * 1000).toFixed(1) : "—"} | ${rng(st.map(s => s.result.satAxisTicks), 0)} | ${st.length ? Math.max(...st.map(s => s.result.dTau0MaxNm)).toFixed(1) : "—"} | ${st.length ? Math.max(...st.map(s => s.result.energyClosurePosJ)).toFixed(3) : "—"} | ${st.length ? Math.min(...st.map(s => s.result.xiStanceMarginMinSSmm)).toFixed(1) : "—"} | ${d.fail ? `step ${d.fail.step}: ${d.fail.why}` : "none"} | ${pd ? Object.entries(pd).map(([k, v]) => `${k}: ${v.recovers && v.vrpOk ? "certifies" : v.why}`).join("; ") : "—"} |`); } }
// CF-4 runs: the gait state at swing initiation (the user's six quantities, walking frame [forward, right]) and the per-step stability trends (transfer + unload + step = one cycle)
if (runs.some(r => r.d.run.cf && /^CF-4/.test(r.d.run.cf))) {
  const cf4 = runs.filter(r => r.d.run.cf && /^CF-4/.test(r.d.run.cf)), v2 = (a, n = 1, k = 1000) => (a ? a.map(x => (x * k).toFixed(n)).join(", ") : "—"), inv = (w) => Object.entries(w || {}).filter(([k]) => /^ankle_[LR]\.z$/.test(k)).reduce((a, [, v]) => a + v, 0);
  console.log("\n# CF-4 schedule summary (v = S / (Tst + planning liftoff delay + swing T); inherited = steps ≥ 2, i.e. swings that follow a previous step's touchdown)\n");
  console.log("| run | Tst s | S m | v plan mm/s | consecutive physical | step period s (≥ 2) | COM fwd at decision, inherited min – max mm/s | ‖v_COM‖ at decision max mm/s | ξ fwd lead at decision mm | ξ lat rel. stance mm | first failure |"); console.log("|---|---|---|---|---|---|---|---|---|---|---|");
  for (const { f, d } of cf4) { const st = d.steps.filter(s => s.cmd && s.cmd.swingInit), inh = st.filter(s => s.k >= 2), rng = (a, n = 1) => (a.length ? `${Math.min(...a).toFixed(n)} – ${Math.max(...a).toFixed(n)}` : "—"), P = d.steps.map(s => s.result && s.result.cf4 && s.result.cf4.stepPeriodS).filter(x => x != null);
    console.log(`| ${f.replace(".json.gz", "")} | ${d.run.cf4.Tst} | ${d.run.cf4.S} | ${(d.run.cf4.vMs * 1000).toFixed(1)} | ${d.physicalSteps} / ${d.run.steps} | ${rng(P, 3)} | ${rng(inh.map(s => s.cmd.swingInit.comV[0] * 1000))} | ${st.length ? Math.max(...st.map(s => s.cmd.swingInit.comSpeed * 1000)).toFixed(1) : "—"} | ${rng(inh.map(s => s.cmd.swingInit.xiRelStance[0] * 1000))} | ${rng(inh.map(s => s.cmd.swingInit.xiRelStance[1] * 1000))} | ${d.fail ? `step ${d.fail.step}, ${d.fail.phase}: ${d.fail.why}` : "none"} |`); }
  console.log("\n# CF-4 gait state at swing initiation (decision tick; liftoff; touchdown) — mm/s and mm, walking frame [forward, right]; loads % BW\n");
  console.log("| run | step | swing | COM v decision | ‖v‖ | ξ rel. stance centroid | ξ̇ = ω(ξ − p) | pelvis v | trailing Fz | stance Fz | since prev. TD s | plan end → release s | COM v liftoff | COM v touchdown |"); console.log("|---|---|---|---|---|---|---|---|---|---|---|---|---|---|");
  for (const { f, d } of cf4) for (const s of d.steps) { const g = s.cmd && s.cmd.swingInit; if (!g) continue; const rc = (s.result && s.result.cf4) || {};
    console.log(`| ${f.replace(".json.gz", "")} | ${s.k} | ${s.swing} | ${v2(g.comV)} | ${(g.comSpeed * 1000).toFixed(1)} | ${v2(g.xiRelStance)} | ${v2(g.xiDot)} | ${v2(g.pelvisV)} | ${(g.trailFzBW * 100).toFixed(2)} | ${(g.stanceFzBW * 100).toFixed(1)} | ${f2(g.sincePrevTouchdownS, 3)} | ${f2(g.planEndToReleaseS, 3)} | ${rc.atLift ? v2(rc.atLift.comV) : "—"} | ${rc.atTouchdown ? v2(rc.atTouchdown.comV) : "—"} |`); }
  console.log("\n# CF-4 per-step stability trends (T = the step's transfer + unload phase before its swing; S = its swing / landing until the landed foot's SUPPORT)\n");
  console.log("| run | step | T ξ err max mm | T shadow abort | S ξ SS margin min mm | S p* out max mm | TD v down / horiz mm/s | foothold err mm | landing lat / fwd err mm | slip T / S mm | sat T + S (ankle inv.) | hard margin min T / S ° | Δτ0 max T / S N·m | energy closure + T / S J | pelvis tilt max ° | pelvis yaw drift ° | foot yaw drift L / R ° | period s |"); console.log("|" + Array(18).fill("---").join("|") + "|");
  for (const { f, d } of cf4) for (const s of d.steps) { const r = s.result, x = s.transfer, c = s.cmd; if (!r || !c) continue; const wl = r.walkLanding || {}, rc = r.cf4 || {};
    console.log(`| ${f.replace(".json.gz", "")} | ${s.k} | ${(x.xiErrMax * 1000).toFixed(1)} | ${x.wouldAbort ? "yes" : "no"} | ${f2(r.xiStanceMarginMinSSmm, 1)} | ${f2(r.pStarOutsideMaxMm, 1)} | ${r.tdVel ? (r.tdVel.down * 1000).toFixed(0) + " / " + (r.tdVel.horiz * 1000).toFixed(0) : "—"} | ${f2(r.tdPosErrMm, 1)} | ${f2(wl.latErrMm, 1)} / ${f2(wl.fwdErrMm, 1)} | ${x.footSlip ? (Math.max(...x.footSlip) * 1000).toFixed(2) : "—"} / ${f2(r.stanceSlipMm)} | ${x.sat} + ${r.satAxisTicks} (${inv(x.satWho) + inv(r.satWho)}) | ${Number.isFinite(x.hardMin) ? x.hardMin.toFixed(1) : "—"} / ${f2(r.legHardMarginMinDeg, 1)} | ${f2(x.dTau0Max, 1)} / ${f2(r.dTau0MaxNm, 1)} | ${f2(x.eClosPos, 3)} / ${f2(r.energyClosurePosJ, 3)} | ${f2(Math.max(x.pelTiltMax || 0, r.pelvisTiltMaxDeg), 2)} | ${f2(c.init.pelvisYawDrift)} | ${c.init.footYawDrift.map(v => f2(v)).join(" / ")} | ${f2(rc.stepPeriodS, 3)} |`); }
}
// CF-5 runs: continuous-walking state per step (forward COM velocity at the decision, liftoff, 0.1 s before touchdown, touchdown, after load acceptance; the cycle minimum;
// the walking capture margin; the single-support VRP; the foothold) — the continuity criteria themselves: review_artifacts/.../loco_cf5_2026-10-08/scripts/cf5_continuity.py
if (runs.some(r => r.d.run.cf && /^CF-5/.test(r.d.run.cf))) {
  const cf5 = runs.filter(r => r.d.run.cf && /^CF-5/.test(r.d.run.cf)), mm = (x, n = 1) => (x == null ? "—" : (x * 1000).toFixed(n)), inv = (w) => Object.entries(w || {}).filter(([k]) => /^ankle_[LR]\.z$/.test(k)).reduce((a, [, v]) => a + v, 0);
  console.log("\n# CF-5 walking plan (per run)\n"); console.log("| run | ω | Ts s | E | σ fwd / lat mm | DCM at touchdown: behind new foot / toward it mm | physical | end |"); console.log("|---|---|---|---|---|---|---|---|");
  for (const { f, d } of cf5) { const W = d.run.cf5.walkPlan || {}; console.log(`| ${f.replace(".json.gz", "")} | ${W.w} | ${W.Ts} | ${W.Es} | ${W.sigmaFwdMm} / ${W.sigmaLatMm} | ${W.dTouchdownBehindNewFootMm} / ${W.latTouchdownTowardNewFootMm} | ${d.physicalSteps} / ${d.run.steps} | ${d.fail ? `FAIL step ${d.fail.step}: ${d.fail.why}` : "no failure"} |`); }
  console.log("\n# CF-5 forward COM velocity through each step (mm/s; walking frame) and the walking state\n");
  console.log("| run | step | swing | decision | liftoff | 0.1 s before TD | touchdown | after acceptance | min in step | lateral at TD | DCM rel. stance at decision (fwd, lat) mm | VRP r rel. stance (fwd, lat) mm | r clamped mm | step chosen m | DCM at TD, both-feet hull margin mm | TD v down mm/s | foothold err mm | sat (ankle inv.) | period s |"); console.log("|" + Array(19).fill("---").join("|") + "|");
  for (const { f, d } of cf5) for (const s of d.steps) { const c = s.cmd, r = s.result || {}, rc = r.cf4 || {}, w = (c && c.walk5) || {}, g = (x) => (x && x.comV ? mm(x.comV[0]) : "—"); if (!c) continue;
    console.log(`| ${f.replace(".json.gz", "")} | ${s.k}${s.tail ? " (tail)" : ""} | ${s.swing} | ${g(c.swingInit)} | ${g(rc.atLift)} | ${g(rc.preTouchdown)} | ${g(rc.atTouchdown)} | ${g(rc.afterAcceptance)} | ${rc.vFwdMinStepMmS ?? "—"} | ${rc.atTouchdown ? mm(rc.atTouchdown.comV[1]) : "—"} | ${w.leadAtDecisionMm ?? "—"}, ${w.latAtDecisionMm ?? "—"} | ${(w.rRelStanceMm || []).join(", ")} | ${w.rClampedMm ?? "—"} | ${w.chosenStepM ?? "—"} | ${rc.atTouchdown ? rc.atTouchdown.xiBothFeetHullMarginMm : "—"} | ${r.tdVel ? mm(r.tdVel.down, 0) : "—"} | ${r.tdPosErrMm ?? "—"} | ${r.satAxisTicks != null ? (s.transfer.sat + r.satAxisTicks) + " (" + (inv(s.transfer.satWho) + inv(r.satWho)) + ")" : "—"} | ${rc.stepPeriodS ?? "—"} |`); }
}
