// ═══ physchar2/tools/vres_analyze.mjs — tables of the vertical-residual DIAGNOSIS (e2/VERTICAL_RESIDUAL_DIAGNOSIS.md) from tools/vres_diag.mjs records. Diagnostic only.
// usage: node tools/vres_analyze.mjs --r1=<dir> --r2=<dir> --r3=<dir> --r4=<dir> --r5=<dir> [--json=<out>]
//   r1: matched factors (vr_<body>_<traj>_<ff>_<hz>_<base>_<turf>); r2: mechanism counterfactuals (A_* turf off, B_* turf on with the SV-2 post-contact sequence, C_* replay / D1
//   pelvis acceleration); r3: B_* with the counterfactual kept through contact (…Run); r4: T-1 trajectories (T_*) and reach conditioning (K_*); r5: lateral reach sweep (S_*, K_*).
// Conventions: the row's reference is the target for the row's own time (tRef = t, verified); ankle error e_y = foot origin − reference (vertical); lowest-point deviation
// d_low = lowest boot point − the reference pose's lowest boot point; orientation part = d_low − e_y. Touchdown metrics as tools/e2_td_metrics.mjs (exact 10 ms window).
import fs from "fs"; import path from "path"; import zlib from "zlib";
const arg = (k, d) => (process.argv.find(a => a.startsWith(`--${k}=`)) || `--${k}=${d}`).split("=").slice(1).join("=");
const L = (f) => JSON.parse(zlib.gunzipSync(fs.readFileSync(f))), ls = (d, pre) => (d && fs.existsSync(d) ? fs.readdirSync(d).filter(f => f.endsWith(".json.gz") && (!pre || f.startsWith(pre))).map(f => path.join(d, f)) : []);
const g = (x, d = 2, w = 6) => (x == null || !isFinite(x) ? "—".padStart(w) : x.toFixed(d).padStart(w)), mean = (a) => a.reduce((s, v) => s + v, 0) / Math.max(1, a.length);
function maxWindowMean(ts, vs, dt, Tw, t0, t1) { const starts = []; for (const t of ts) { starts.push(t - dt, t - Tw, t - dt - Tw, t); } let best = 0;
  for (const a of starts) { if (a < t0 - 1e-9 || a > t1 + 1e-9) continue; let acc = 0; for (let j = 0; j < ts.length; j++) { const lo = Math.max(ts[j] - dt, a), hi = Math.min(ts[j], a + Tw); if (hi > lo) acc += vs[j] * (hi - lo); } best = Math.max(best, acc / Tw); } return best; }
function residual(r) { const T = r.tr.T, wn = r.wn, sw = r.rows.filter(x => x.ph === "swing" && x.u != null && x.u >= -1e-9), at = (ph) => sw.find(q => q.u / T >= ph - 1e-9) || null;
  const ey = (x) => (x ? 1000 * (x.foot.p[1] - x.ref.p[1]) : null), dl = (x) => (x ? 1000 * (x.low - x.lowRef) : null); let n3 = 0, d3 = 0, ny = 0, dy = 0;
  for (const x of sw.filter(q => q.u / T <= 0.8 + 1e-9)) for (let i = 0; i < 3; i++) { const ga = -x.ref.a[i] / (wn * wn), e = x.foot.p[i] - x.ref.p[i]; n3 += e * ga; d3 += ga * ga; if (i === 1) { ny += e * ga; dy += ga * ga; } }
  const o = { n3, d3, ny, dy, ey: {}, dl: {}, rot: {} }; for (const ph of [0.75, 0.8, 0.85, 0.9, 1.0]) { const x = at(ph); o.ey[ph] = ey(x); o.dl[ph] = dl(x); o.rot[ph] = x ? dl(x) - ey(x) : null; }
  const w = sw.filter(q => q.u / T >= 0.75 - 1e-9 && q.u / T <= 0.8 + 1e-9); o.bin = w.length ? Math.min(...w.map(dl)) : null; return o; }
function touchdown(r) { if (r.events.tC == null) return null; const dt = 1 / r.hz, tC = r.events.tC, rows = r.rows, n = r.swing, iC = rows.findIndex(x => x.t >= tC - 1e-9), pre = rows[iC - 1];
  const span = rows.filter(x => x.t >= tC - 2 * dt - 1e-9 && x.t <= tC + 0.1 + 1e-9), rs = Math.max(1, 240 / r.hz), nw = r.hz === 240 ? 2 : Math.max(2, Math.ceil(2 * r.hz / 240)), onset = new Set();
  for (let i = 1; i < rows.length; i++) if ((rows[i - 1].touch || 0) === 0 && (rows[i].touch || 0) > 0) for (let j = 0; j < nw; j++) onset.add(i + j);
  const tauOf = (x) => x.joints.flatMap(j => j.ax.map(a => (a ? a.tauPrev : null))); let viol = 0;
  for (let i = 1; i < rows.length; i++) { if (rows[i].t < tC - 2 * dt - 1e-9) continue; const a = tauOf(rows[i]), b = tauOf(rows[i - 1]); let m = 0; a.forEach((v, k) => { if (v != null && b[k] != null) m = Math.max(m, Math.abs(v - b[k])); }); if (m > (onset.has(i) ? 25 : 10) * rs) viol++; }
  const loss = r.trans.filter(q => q.n === n && q.t > tC && q.from === "TOUCHDOWN" && q.to === "AIRBORNE").length, touch = rows.filter(x => x.t >= tC - 1e-9 && x.t <= tC + 0.05).map(x => x.touch);
  return { phiC: r.events.phiC, delta: 1000 * pre.lowRef, vN: -pre.foot.v[1], vRef: -pre.ref.v[1], peak: 100 * Math.max(...span.map(x => x.Fz)) / r.W, w10: 100 * maxWindowMean(span.map(x => x.t), span.map(x => x.Fz), dt, 0.010, tC - 3 * dt, tC + 0.09) / r.W, viol, loss, touch0: touch[0], flatTicks: touch.findIndex(v => v === Math.max(...touch)) }; }
const runs = []; const add = (f, tag) => { const r = L(f), b = path.basename(f, ".json.gz"); runs.push({ f: b, tag, body: r.human, traj: r.traj, hz: r.hz, ff: r.ff, base: r.base, turf: r.turf, x: JSON.stringify(r.xswing || {}), scope: r.xscope || "run", dy: r.tr.dy, res: residual(r), td: touchdown(r) }); };
for (const f of ls(arg("r1", ""), "vr_")) add(f, "r1"); for (const f of ls(arg("r2", ""))) add(f, "r2"); for (const f of ls(arg("r3", ""))) add(f, "r3"); for (const f of ls(arg("r4", ""))) add(f, "r4"); for (const f of ls(arg("r5", ""))) add(f, "r5");
const V = { base: (r) => r.tag === "r1" && r.ff === "on" && r.base === "float" && r.turf === "off", fixed: (r) => r.tag === "r1" && r.ff === "on" && r.base === "fixed" && r.turf === "off", replay: (r) => r.base === "replay", d1pa: (r) => r.x.includes("diagD1PelAcc"),
  vp: (r) => r.tag === "r2" && r.f.startsWith("A_") && r.base === "float" && r.x === '{"vffPassive":true}', sr: (r) => r.tag === "r2" && r.f.startsWith("A_") && r.x === '{"vffRate":"srAll"}', vpsr: (r) => r.tag === "r2" && r.f.startsWith("A_") && r.x.includes("srAll") && r.x.includes("vffPassive"), fixvp: (r) => r.tag === "r2" && r.f.startsWith("A_") && r.base === "fixed" };
console.log(`records ${runs.length}`);
console.log("\n1. RESIDUAL (turf removed, D1 on), mean over 3 bodies × 3 rates (replay / D1-pelvis-acceleration: 240 Hz × 3 bodies): lowest-point deviation d_low (mm) at φ 0.80 / 0.85 / 0.90 / 1.0 | ankle e_y φ 0.85 / 1.0 | orientation part φ 0.85 | min d_low over [0.75, 0.80] | vertical β");
const T1 = {}; for (const tr of ["V0", "R-F", "R-L", "H-T45"]) { console.log(tr); for (const [nm, fn] of Object.entries(V)) { const s = runs.filter(r => fn(r) && r.traj === tr); if (!s.length) continue; const m = (k) => mean(s.map(k));
  console.log(`  ${nm.padEnd(7)} ${[0.8, 0.85, 0.9, 1].map(p => g(m(r => r.res.dl[p]))).join("")} | ${g(m(r => r.res.ey[0.85]))}${g(m(r => r.res.ey[1]))} | ${g(m(r => r.res.rot[0.85]))} | ${g(m(r => r.res.bin))} | ${g(s.reduce((a, r) => a + r.res.ny, 0) / s.reduce((a, r) => a + r.res.dy, 0))}  (${s.length})`); } }
console.log("\n2. DECOMPOSITION of d_low (mm, mean over bodies × rates), two orders: pelvis-motion coupling (base − sr), orientation (sr − vpsr) and the remainder (vpsr); alt. orientation (base − vp), coupling (vp − vpsr); servo-only remainder with a fixed pelvis (fixvp)");
for (const tr of ["V0", "R-F", "R-L", "H-T45"]) for (const ph of [0.8, 0.85, 0.9]) { const M = (fn) => mean(runs.filter(r => fn(r) && r.traj === tr).map(r => r.res.dl[ph])), b = M(V.base), sr = M(V.sr), vp = M(V.vp), vs = M(V.vpsr), fv = M(V.fixvp);
  console.log(`  ${tr.padEnd(6)} φ ${ph.toFixed(2)}  total ${g(b)} = coupling ${g(b - sr)} + orientation ${g(sr - vs)} + remainder ${g(vs)}   | alt: orientation ${g(b - vp)} + coupling ${g(vp - vs)}   | fixed-pelvis servo remainder ${g(fv)}`); }
console.log("\n3. RATE dependence of the servo-only remainder (fixed pelvis + passive compensation), d_low φ 0.90 mean over bodies × trajectories: " + [180, 240, 480].map(h => `${h} Hz ${g(mean(runs.filter(r => V.fixvp(r) && r.hz === h).map(r => r.res.dl[0.9])))}`).join("  "));
console.log("\n4. T-1 (pooled β over axes, bodies, rates; SV-2 definition) — base / fixed / sr / vpsr:");
for (const tr of ["C-F7", "C-L5", "R-F", "R-L", "V0", "H-T45"]) { const pool = (fn) => { const s = runs.filter(r => fn(r) && r.traj === tr); return s.length ? s.reduce((a, r) => a + r.res.n3, 0) / s.reduce((a, r) => a + r.res.d3, 0) : null; };
  const t4 = (v) => (r) => r.tag === "r4" && r.f.startsWith("T_") && r.f.endsWith("_" + v); console.log(`  ${tr.padEnd(6)} ${["base", "fixed", "sr", "vpsr"].map(v => g(pool(tr.startsWith("C-") ? t4(v) : V[v]), 3)).join("")}`); }
console.log("\n5. TOUCHDOWN (turf on, SV-2 post-contact; 3 bodies × 3 rates per cell): mean φ_c | mean δ (reference lowest point at contact, mm) | mean / max approach speed | max exact-10 ms load %BW (runs > 25) | runs with E1a-7 violations (swing-leg axes) | runs with contact loss | mean pieces at first contact");
const VB = { base: (r) => r.f.endsWith("_base"), vp: (r) => r.f.endsWith("_vp"), sr: (r) => r.f.endsWith("_sr"), vpsr: (r) => r.f.endsWith("_vpsr"), "vp(run)": (r) => r.f.endsWith("_vpRun"), "sr(run)": (r) => r.f.endsWith("_srRun"), "vpsr(run)": (r) => r.f.endsWith("_vpsrRun") };
for (const tr of ["R-F", "R-L", "H-T45", "H-F15", "H-D"]) { console.log(tr); for (const [nm, fn] of Object.entries(VB)) { const s = runs.filter(r => r.f.startsWith("B_") && fn(r) && r.traj === tr && r.td); if (!s.length) continue; const t = s.map(r => r.td);
  console.log(`  ${nm.padEnd(9)} ${g(mean(t.map(x => x.phiC)), 3)} | ${g(mean(t.map(x => x.delta)))} | ${g(mean(t.map(x => x.vN)), 3)}${g(Math.max(...t.map(x => x.vN)), 3)} | ${g(Math.max(...t.map(x => x.w10)), 1)} (${t.filter(x => x.w10 > 25).length}) | ${String(t.filter(x => x.viol > 0).length).padStart(2)} | ${String(t.filter(x => x.loss > 0).length).padStart(2)} | ${g(mean(t.map(x => x.touch0)), 1)}`); } }
{ const B = runs.filter(r => r.f.startsWith("B_") && r.td && r.td.delta > 0.02), lx = B.map(r => Math.log(r.td.delta)), ly = B.map(r => Math.log(r.td.vRef)), mx = mean(lx), my = mean(ly); let sxy = 0, sxx = 0, syy = 0; for (let i = 0; i < B.length; i++) { sxy += (lx[i] - mx) * (ly[i] - my); sxx += (lx[i] - mx) ** 2; syy += (ly[i] - my) ** 2; }
  console.log(`\n6. CONTACT SPEED LAW over ${B.length} touchdowns: reference speed at contact ∝ δ^${(sxy / sxx).toFixed(3)} (r ${(sxy / Math.sqrt(sxx * syy)).toFixed(3)}); prefactor at δ = 1 mm ${Math.exp(my - (sxy / sxx) * mx).toFixed(4)} m/s`); }
console.log("\n7. REACH (V2-long-legs, 240 Hz, turf removed): lateral offset | D1 | variant | runaway φ (first applied Δτ > 10 N·m) | max applied Δτ");
for (const r of runs.filter(r => r.tag === "r5" || (r.tag === "r4" && r.f.startsWith("K_"))).sort((a, b) => a.dy - b.dy || a.f.localeCompare(b.f))) { const rr = L(path.join(arg(r.tag, ""), r.f + ".json.gz")), T = rr.tr.T, R = rr.rows.filter(q => q.ph === "swing" && q.u >= 0 && q.u / T <= 1.2);
  let mx = 0, tr0 = null; for (let i = 1; i < R.length; i++) { const a = R[i].joints.flatMap(j => j.ax.map(x => (x ? x.tauPrev : null))), b = R[i - 1].joints.flatMap(j => j.ax.map(x => (x ? x.tauPrev : null))); let m = 0; a.forEach((v, k) => { if (v != null && b[k] != null) m = Math.max(m, Math.abs(v - b[k])); }); mx = Math.max(mx, m); if (m > 10 && tr0 == null) tr0 = R[i].u / T; }
  const kmax = Math.max(...R.filter(q => q.xs).map(q => Math.abs(q.xs[3]) * 180 / Math.PI)); console.log(`  ${g(r.dy, 3)} ${r.ff.padEnd(3)} ${r.base.padEnd(6)} ${r.x.padEnd(28)} ${tr0 != null ? g(tr0, 3) : "  none"} ${g(mx, 1, 8)}  max knee flexion target ${g(kmax, 1)}°`); }
if (arg("json", "")) fs.writeFileSync(arg("json", ""), JSON.stringify(runs));
