const fs=require("fs"), z=require("zlib"); const L=f=>JSON.parse(z.gunzipSync(fs.readFileSync(f)));
const mode=process.argv[2];
if (mode==="cl11") { for (const f of fs.readdirSync(".").filter(f=>f.includes("C-L11")&&f.endsWith(".gz"))) { const r=L(f), se=r.series; const i0=se.dTau0.findIndex(v=>v>30*240/r.hz); const mx=Math.max(...se.dTau0); const tc=r.events.tC, tlo=r.events.tLo;
  console.log(f.padEnd(44), "dTau0 max", mx.toExponential(2), "first>lim t", i0>=0?se.t[i0].toFixed(4):"-", "phi", i0>=0?((se.t[i0]-tlo)/r.tr.T).toFixed(3):"-", "tC phi", r.events.phiC&&r.events.phiC.toFixed(3), "TD entries", r.trans.filter(q=>q.n===r.swing&&q.to==="TOUCHDOWN"&&q.t>=tlo).length); } }
if (mode==="td") { for (const f of process.argv.slice(3)) { const r=L(f), n=r.swing, tlo=r.events.tLo, T=r.tr.T; const tr=r.trans.filter(q=>q.n===n&&q.t>=tlo-1e-9); const R=r.rows;
  const iC=R.findIndex(x=>x.t>=r.events.tC-1e-9), pre=R[iC-1];
  console.log(f, "phiC", r.events.phiC.toFixed(3), "approach v", pre.foot.v.map(v=>v.toFixed(3)).join(","), "trans", tr.map(q=>`${q.from}->${q.to}@${((q.t-tlo)/T).toFixed(3)}(${q.t.toFixed(3)})`).join(" "), "cleared", r.events.cleared&&r.events.cleared.toFixed(3), "tRet", r.events.tRet&&r.events.tRet.toFixed(3));
  const after=R.filter(x=>x.t>=r.events.tC-0.01&&x.t<=r.events.tC+0.25); after.filter((x,i)=>i%2===0).forEach(x=>console.log("   ", x.t.toFixed(4), x.ph, "touch", JSON.stringify(x.touch), "Fz", x.Fz.toFixed(1), "low", x.low.toFixed(2), "v", x.foot.v.map(v=>v.toFixed(3)).join(","), "st", JSON.stringify(x.st), "ref", x.ref? x.ref.p.map(v=>v.toFixed(4)).join(","):"-", "foot", x.foot.p.map(v=>v.toFixed(4)).join(","))); } }
if (mode==="i2") { const lim=(hz,onset)=>(onset?25:10)*Math.max(1,240/hz); for (const f of process.argv.slice(3)) { const r=L(f), se=r.series, e=r.events, nw=r.hz===240?2:Math.max(2,Math.ceil(2*r.hz/240)); const exc=new Set(); se.onset.forEach((o,i)=>{ if(o) for(let j=0;j<nw;j++) exc.add(i+j); });
  se.t.forEach((t,i)=>{ if (t<0.5) return; const L1=lim(r.hz,exc.has(i)); const c0=30*240/r.hz; if (se.dTau[i]>L1||se.dTau0[i]>c0) { const rel=[["tCmd",e.tCmd],["tLo",e.tLo],["tC",e.tC],["cleared",e.cleared],["tRet",e.tRet]].map(([k,v])=>v!=null?`${k}${(t-v>=0?"+":"")}${(t-v).toFixed(3)}`:"").join(" "); console.log(f.padEnd(46), t.toFixed(4), "dTau", se.dTau[i].toFixed(2), "/", L1.toFixed(1), "dTau0", se.dTau0[i].toFixed(2), "/", c0.toFixed(1), rel); } }); } }
if (mode==="beta") { for (const id of ["R-F","R-L","C-F7","C-F13","C-L5"]) { const acc={on:[0,0,0,0,0,0],off:[0,0,0,0,0,0]}; let fitB={on:[],off:[]};
  for (const f of fs.readdirSync(".").filter(f=>f.endsWith(`_${id}.json.gz`))) { const r=L(f), ff=r.ff, T=r.tr.T, wn=r.wn; for (const x of r.rows) { if (!(x.ph==="swing"&&x.u!=null&&x.u>=-1e-9&&x.u/T<=0.8+1e-9)) continue; for (let i=0;i<3;i++){ const q=x.foot.p[i]-x.ref.p[i], ga=-x.ref.a[i]/(wn*wn); acc[ff][2*i]+=q*ga; acc[ff][2*i+1]+=ga*ga; } } }
  console.log(id, ["on","off"].map(ff=>`${ff}: x ${(acc[ff][0]/acc[ff][1]).toFixed(3)} y ${(acc[ff][2]/acc[ff][3]).toFixed(3)} z ${(acc[ff][4]/acc[ff][5]).toFixed(3)} | den share x/y/z ${[1,3,5].map(k=>(acc[ff][k]/(acc[ff][1]+acc[ff][3]+acc[ff][5])).toFixed(2)).join("/")}`).join("  ")); } }
