import fs from "fs"; import path from "path";
const PC = process.argv[2], ROOT = path.resolve(PC, "../../.."), KEYS = process.argv[3].split(","), T0 = +(process.argv[4] || 0.95), T1 = +(process.argv[5] || 2.0), EVERY = +(process.argv[6] || 12);
const { buildBodySpec } = await import(PC + "/pc_body.js"); const { loadJolt } = await import(PC + "/pc_jolt.js"); const C1 = await import(PC + "/pc_gatec1.js");
const dir = path.join(ROOT, "assets/characters/outfield/gabriel"), rig = JSON.parse(fs.readFileSync(path.join(dir, "rig.json"), "utf8")), buf = fs.readFileSync(path.join(dir, "mesh.bin"));
const ab = buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength), L = rig.mesh.layout, T = { Float32Array, Uint16Array, Uint32Array, Uint8Array };
const mesh = {}; for (const k of ["positions", "joints", "weights", "indices"]) mesh[k] = new T[L[k].elementType](ab, L[k].byteOffset, L[k].elementCount);
const spec = buildBodySpec(rig, mesh), J = await loadJolt(PC + "/vendor/jolt-physics.wasm-compat.js");
for (const key of KEYS) { const r = C1.runC1(J, spec, key, { seconds: +(process.argv[7] || 0) || undefined }); console.log(`=== ${key} ${r.outcome} classTimes ${JSON.stringify(r.classTimes)} reason: ${r.fallReason}`);
  for (const q of r.recs.filter((x, i) => x.t >= T0 && x.t <= T1 && i % EVERY === 0)) console.log(`t ${q.t.toFixed(3)} ${q.cls.padEnd(20)} ξm ${(q.xiMargin * 100).toFixed(1).padStart(7)} cm  com z ${q.com[2].toFixed(3)} x ${q.com[0].toFixed(3)} y ${q.com[1].toFixed(3)}  v [${q.vcom.map(v => v.toFixed(2))}]  trunk ${q.trunk.toFixed(1)} spine ${q.spine.toFixed(1)}  feet ${q.feet.L.state}/${q.feet.R.state} loads ${q.feet.L.load.toFixed(0)}/${q.feet.R.load.toFixed(0)}  p* ${q.ctl ? q.ctl.pStar.map(v => v.toFixed(3)) : "-"} r ${q.ctl ? (Math.hypot(...q.ctl.r) * 100).toFixed(1) : "-"}cm hipCap ${q.ctl ? (q.ctl.hipCap * 100).toFixed(1) : "-"}  ankleEff ${q.J[9].eff.toFixed(2)}/${q.J[12].eff.toFixed(2)} hipEff ${q.J[7].eff.toFixed(2)}/${q.J[10].eff.toFixed(2)}`); }
