import fs from "fs"; import path from "path";
const PC = process.argv[2], ROOT = path.resolve(PC, "../../.."), KEY = process.argv[3], T0 = +process.argv[4], T1 = +process.argv[5], EVERY = +(process.argv[6] || 12), SW = process.argv[7] || "R";
const { buildBodySpec } = await import(PC + "/pc_body.js"); const { loadJolt } = await import(PC + "/pc_jolt.js"); const C2 = await import(PC + "/pc_gatec2.js"); const { Q, V } = await import(PC + "/pc_math.js"); const { jointState } = await import(PC + "/pc_gatea.js");
const dir = path.join(ROOT, "assets/characters/outfield/gabriel"), rig = JSON.parse(fs.readFileSync(path.join(dir, "rig.json"), "utf8")), buf = fs.readFileSync(path.join(dir, "mesh.bin"));
const ab = buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength), L = rig.mesh.layout, T = { Float32Array, Uint16Array, Uint32Array, Uint8Array };
const mesh = {}; for (const k of ["positions", "joints", "weights", "indices"]) mesh[k] = new T[L[k].elementType](ab, L[k].byteOffset, L[k].elementCount);
const spec = buildBodySpec(rig, mesh), J = await loadJolt(PC + "/vendor/jolt-physics.wasm-compat.js"), r = C2.runC2(J, spec, KEY, { keepStates: true });
const bi = (n) => spec.bodies.findIndex(b => b.name === n), fj = spec.bodies[bi("foot_" + SW)], ja = spec.joints.find(j => j.name === "ankle_" + SW), jk = spec.joints.find(j => j.name === "knee_" + SW), jh = spec.joints.find(j => j.name === "hip_" + SW);
console.log("ankle limits", JSON.stringify(ja.limits), "knee", jk.lo, jk.hi, "hip", JSON.stringify(jh.limits));
for (let i = 0; i < r.recs.length; i += EVERY) { const q = r.recs[i]; if (q.t < T0 || q.t > T1) continue; const S = q.states, f = S[bi("foot_" + SW)], fz = Q.rot(f.rot, [0, 0, 1]), fx = Q.rot(f.rot, [1, 0, 0]);
  const a = jointState(ja, S), k = jointState(jk, S), h = jointState(jh, S), tg = q.swingTgt;
  console.log(`t ${q.t.toFixed(2)} ${String(q.reqStage).padEnd(8)} foot pos ${f.pos.map(v => v.toFixed(3))} tgt ${tg ? tg.pos.map(v => v.toFixed(3)) : "-"} pitch(toe-down +) ${(-Math.asin(fz[1]) * 57.3).toFixed(1)} roll ${(Math.asin(fx[1]) * 57.3).toFixed(1)} | ankle tw ${a.twist.toFixed(1)} sY ${a.swingY.toFixed(1)} sZ ${a.swingZ.toFixed(1)} | knee ${k.a.toFixed(1)} | hip tw ${h.twist.toFixed(1)} sY ${h.swingY.toFixed(1)} sZ ${h.swingZ.toFixed(1)} | ${q.feet[SW].touching ? "TOUCH" : ""} man ${q.feet[SW].manifold} pts ${q.feet[SW].points.length} load ${q.feet[SW].load.toFixed(0)} cts ${q.cts.filter(c => (c.a === bi("foot_" + SW) || c.b === bi("foot_" + SW))).map(c => `${c.a}/${c.b}:${(c.depth * 1000).toFixed(1)}`).join(" ")}`); }
