// forward / lateral / backward placement sweep for the V1.1 working controller: outcome + the physical quantities during acceptance
import fs from "fs"; import path from "path";
const PC = process.argv[2], ROOT = path.resolve(PC, "../../.."), CAL = process.argv[3], DIR = process.argv[4] || "fwd", LIST = (process.argv[5] || "0.14,0.18,0.20,0.22,0.24,0.26").split(",").map(Number);
const { buildBodySpec } = await import(PC + "/pc_body.js"); const { loadJolt } = await import(PC + "/pc_jolt.js"); const C2 = await import(PC + "/pc_gatec2.js");
const dir = path.join(ROOT, "assets/characters/outfield/gabriel"), rig = JSON.parse(fs.readFileSync(path.join(dir, "rig.json"), "utf8")), buf = fs.readFileSync(path.join(dir, "mesh.bin"));
const ab = buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength), L = rig.mesh.layout, T = { Float32Array, Uint16Array, Uint32Array, Uint8Array };
const mesh = {}; for (const k of ["positions", "joints", "weights", "indices"]) mesh[k] = new T[L[k].elementType](ab, L[k].byteOffset, L[k].elementCount);
const spec = buildBodySpec(rig, mesh, { calib: CAL }), J = await loadJolt(PC + "/vendor/jolt-physics.wasm-compat.js"), ji = (n) => spec.joints.findIndex(j => j.name === n);
const ctrl = process.env.CTRL ? JSON.parse(process.env.CTRL) : undefined, out = [];
for (const X of LIST) { const ANG = DIR.startsWith("ang") ? +DIR.slice(3) * Math.PI / 180 : null, key = `SW_${DIR}_${X}`, fw = ANG != null ? X * Math.cos(ANG) : DIR === "fwd" ? X : DIR === "bwd" ? -X : DIR === "diag" ? X * 0.7071 : 0, ow = ANG != null ? X * Math.sin(ANG) : DIR === "lat" ? X : DIR === "diag" ? X * 0.7071 : 0;
  C2.TESTS_C2[key] = { group: "sweep", title: key, seconds: +(process.env.SECS || 11), requests: [{ type: "place", foot: process.env.FOOT || "R", forward: fw, outward: ow, at: 0.5 }] };
  const r = C2.runC2(J, spec, key, { keepStates: true, ctrl }), q = r.requests.find(x => x.type !== "shift"), acc = r.recs.filter(x => x.reqStage === "ACCEPT"), ss = r.recs.filter(x => ["SWING", "ALIGN", "DESCEND"].includes(x.reqStage));
  const pk = (set, n) => set.length ? Math.max(...set.map(x => x.J[ji(n)].eff)) : null, p0 = r.recs[0].states[0].pos[1], pmin = Math.min(...r.recs.map(x => x.states[0].pos[1]));
  const lost = r.recs.find(x => ["STEP_NEEDED", "FALLING", "UNRECOVERABLE", "GROUNDED"].includes(x.cls));
  // touchdown quality: steps after touchdown on which the LANDED foot is off the ground (bounce), and the landed foot's peak slide
  const bounce = acc.filter(x => !x.feet.R.touching).length, kneeRomMin = r.recs.length ? Math.min(...r.recs.filter(x => x.reqStage).map(x => x.limMarginDeg ?? 99)) : null;
  const pitchSat = (set, n) => set.filter(x => x.J[ji(n)].sat && (x.J[ji(n)].satAx || []).includes(1)).length, hingeSat = (set, n) => set.filter(x => x.J[ji(n)].sat).length;
  const row = { X, status: q.status, why: (q.why || "").slice(0, 70), feasible: q.feasible, corr: q.correctedCm, tdErr: q.touchdown && q.touchdown.landingErrorCm, tdV: q.touchdown && [q.touchdown.verticalVelocity, q.touchdown.horizontalVelocity],
    accS: q.accepted && q.accepted.fromTouchdownS, pelvisDropCm: +((p0 - pmin) * 100).toFixed(1), accMinXiM: acc.length ? +(Math.min(...acc.map(x => x.xiMargin)) * 100).toFixed(1) : null, lostAt: lost ? +lost.t.toFixed(2) : null, lostStage: lost ? lost.reqStage : null,
    effAcc: { kneeL: pk(acc, "knee_L"), kneeR: pk(acc, "knee_R"), ankL: pk(acc, "ankle_L"), ankR: pk(acc, "ankle_R"), hipL: pk(acc, "hip_L"), hipR: pk(acc, "hip_R") },
    effSS: { kneeL: pk(ss, "knee_L"), ankL: pk(ss, "ankle_L"), hipL: pk(ss, "hip_L") }, sat: q.metrics && q.metrics.saturationMs, ankle: q.metrics && q.metrics.ankle, hash: r.hash,
    bounceMs: +(bounce / 0.24).toFixed(0), limMargin: q.metrics && q.metrics.jointLimitMarginDeg, limJoint: q.metrics && q.metrics.jointLimitMarginJoint,
    kneeSatMs: +((hingeSat(acc.concat(ss), "knee_L") + hingeSat(acc.concat(ss), "knee_R")) / 0.24).toFixed(0), anklePitchSatMs: +((pitchSat(acc.concat(ss), "ankle_L") + pitchSat(acc.concat(ss), "ankle_R")) / 0.24).toFixed(0),
    hipPitchSatMs: +((pitchSat(acc.concat(ss), "hip_L") + pitchSat(acc.concat(ss), "hip_R")) / 0.24).toFixed(0) };
  out.push(row); if (!process.env.LONG) { console.log(`${DIR} ${X.toFixed(2)} ${row.status.padEnd(7)} feas ${JSON.stringify(row.feasible)} corr ${row.corr} | bounce ${row.bounceMs} ms · lim ${row.limMargin}° ${row.limJoint} · sat knee ${row.kneeSatMs} ankPitch ${row.anklePitchSatMs} hipPitch ${row.hipPitchSatMs} ms | td err ${row.tdErr} v ${JSON.stringify(row.tdV)} | acc ${row.accS} s | drop ${row.pelvisDropCm} cm | acc ξm min ${row.accMinXiM} | lost ${row.lostAt} ${row.lostStage || ""} ${row.status === "DONE" ? "" : row.why}`); continue; } const e = (o) => Object.entries(o).map(([k, v]) => `${k} ${v == null ? "-" : v.toFixed(2)}`).join(" ");
  console.log(`${DIR} ${X.toFixed(2)} ${row.status.padEnd(8)} bounce ${row.bounceMs} ms · lim ${row.limMargin}° (${row.limJoint}) · sat knee ${row.kneeSatMs} ankPitch ${row.anklePitchSatMs} hipPitch ${row.hipPitchSatMs} ms |`); if (0) console.log(`${DIR} ${X.toFixed(2)} ${row.status.padEnd(8)} feas ${JSON.stringify(row.feasible)} corr ${row.corr} | td err ${row.tdErr} v ${JSON.stringify(row.tdV)} | acc ${row.accS} s | pelvis drop ${row.pelvisDropCm} cm | acc ξm min ${row.accMinXiM} | lost ${row.lostAt} ${row.lostStage || ""}\n      eff ACC ${e(row.effAcc)} | SS ${e(row.effSS)} | sat ${JSON.stringify(row.sat)} | stDF ${row.ankle && row.ankle.stance.maxDorsiDeg} swDF ${row.ankle && row.ankle.swing.maxDorsiDeg} ${row.why}`); }
if (process.env.OUT) fs.writeFileSync(process.env.OUT, JSON.stringify(out, null, 1));
