import fs from "fs"; import path from "path";
const PC = process.argv[2], ROOT = path.resolve(PC, "../../.."), TESTK = process.argv[3], AT = +process.argv[4];
const { buildBodySpec, shapeLowestY } = await import(PC + "/pc_body.js"); const { loadJolt } = await import(PC + "/pc_jolt.js"); const G = await import(PC + "/pc_gateb.js"); const { Q, V, deg } = await import(PC + "/pc_math.js");
const dir = path.join(ROOT, "assets/characters/outfield/gabriel"), rig = JSON.parse(fs.readFileSync(path.join(dir, "rig.json"), "utf8")), buf = fs.readFileSync(path.join(dir, "mesh.bin"));
const ab = buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength), L = rig.mesh.layout, T = { Float32Array, Uint16Array, Uint32Array, Uint8Array };
const mesh = {}; for (const k of ["positions", "joints", "weights", "indices"]) mesh[k] = new T[L[k].elementType](ab, L[k].byteOffset, L[k].elementCount);
const spec = buildBodySpec(rig, mesh), J = await loadJolt(PC + "/vendor/jolt-physics.wasm-compat.js");
const r = G.runTest(J, spec, TESTK, { keepStates: true }), rec = r.recs[Math.round(AT * 240)], f = (v) => "[" + v.map(x => x.toFixed(3)).join(",") + "]";
console.log("contacts:", rec.cts.map(c => `${c.a < 0 ? "turf" : spec.bodies[c.a].name}–${c.b < 0 ? "turf" : spec.bodies[c.b].name} ${(c.depth * 1000).toFixed(1)}mm n${f(c.normal)}`).join(" | "));
rec.states.forEach((s, i) => console.log(`${spec.bodies[i].name.padEnd(11)} pos ${f(s.pos)} lowest ${Math.min(...spec.bodies[i].shapes.map(sh => shapeLowestY(sh, s.pos, s.rot))).toFixed(3)} v ${f(s.v)} w ${f(s.w)}`));
console.log("support F", rec.sup && f(rec.sup.F), "T", rec.sup && f(rec.sup.T));
