import fs from "fs"; import path from "path";
const PC = process.argv[2], ROOT = path.resolve(PC, "../../.."), CAL = process.argv[3], TEST = process.argv[4] || "B_lift_R", TS = (process.argv[5] || "1.0,1.6,2.0,2.4,2.9").split(",").map(Number);
const { buildBodySpec } = await import(PC + "/pc_body.js"); const { loadJolt } = await import(PC + "/pc_jolt.js"); const C2 = await import(PC + "/pc_gatec2.js"); const { Q, V } = await import(PC + "/pc_math.js"); const { jointState } = await import(PC + "/pc_gatea.js");
const dir = path.join(ROOT, "assets/characters/outfield/gabriel"), rig = JSON.parse(fs.readFileSync(path.join(dir, "rig.json"), "utf8")), buf = fs.readFileSync(path.join(dir, "mesh.bin"));
const ab = buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength), L = rig.mesh.layout, T = { Float32Array, Uint16Array, Uint32Array, Uint8Array };
const mesh = {}; for (const k of ["positions", "joints", "weights", "indices"]) mesh[k] = new T[L[k].elementType](ab, L[k].byteOffset, L[k].elementCount);
const spec = buildBodySpec(rig, mesh, { calib: CAL }), J = await loadJolt(PC + "/vendor/jolt-physics.wasm-compat.js"), r = C2.runC2(J, spec, TEST, { keepStates: true, ctrl: Object.assign({}, process.env.RECAL ? { anticipateReach: true } : {}, process.env.DIAG ? { diagUnload: true } : {}) });
const bi = (n) => spec.bodies.findIndex(b => b.name === n), ji = (n) => spec.joints.findIndex(j => j.name === n), Lr = V.dist(spec.bodies[bi("shin_R")].origin, spec.bodies[bi("thigh_R")].origin) + V.dist(spec.bodies[bi("foot_R")].origin, spec.bodies[bi("shin_R")].origin);
for (const t of TS) { const q = r.recs.find(x => Math.abs(x.t - t) < 0.003); if (!q) continue; const S = q.states, hip = S[bi("thigh_R")].pos, ank = S[bi("foot_R")].pos, d = V.dist(hip, ank), kn = jointState(spec.joints[ji("knee_R")], S).a * 57.3;
  const kA = jointState(spec.joints[ji("ankle_R")], S), lim = spec.joints[ji("ankle_R")]; const sw = q.ctl && q.ctl.swing; const fb = q.ctl && q.ctl.feetBal; console.log(`${CAL} t ${t} ankR Y ${(kA.swingY*57.3).toFixed(1)} [${lim.swingY}] Z ${(kA.swingZ*57.3).toFixed(1)} [${lim.swingZ.map(v=>v.toFixed(1))}] pd ${JSON.stringify(q.ctl && q.ctl.pdTrace, (k, v) => typeof v === "number" ? +v.toFixed(3) : v)} ankR y ${ank[1].toFixed(3)} x ${ank[0].toFixed(3)} z ${ank[2].toFixed(3)} · ${String(q.reqStage).padEnd(8)} loads L ${q.feet.L.load.toFixed(0)} R ${q.feet.R.load.toFixed(0)} | R leg hip→ankle ${d.toFixed(3)} / ${Lr.toFixed(3)} = ${(100 * d / Lr).toFixed(1)}% · knee ${kn.toFixed(1)}° · R hip x ${hip[0].toFixed(3)} y ${hip[1].toFixed(3)} · pelvis y ${S[0].pos[1].toFixed(3)} PdY ${q.ctl ? q.ctl.pelvisTarget.pos[1].toFixed(3) : "-"} | want R share ${fb && fb.R ? fb.R.share.toFixed(2) : "-"} · ξ ${q.xi.map(v => v.toFixed(3))} p* ${q.ctl ? q.ctl.pStar.map(v => v.toFixed(3)) : "-"} · knee_R τ ${(q.J[ji("knee_R")].lam * 240).toFixed(0)} hip_R τ ${q.J[ji("hip_R")].lam.map(x => (x * 240).toFixed(0))} ankle_R τ ${q.J[ji("ankle_R")].lam.map(x => (x * 240).toFixed(0))}`); }
