// node probe_layers.js <out.json> <TEST|COURTOIS> <band> <fixtures> — per-tick LAYER contributions of the dive presentation
const NM = process.env.PUPPETEER_NODE_MODULES; if (NM) module.paths.unshift(NM);
const puppeteer = require("puppeteer-core"), fs = require("fs"); const [OUT, CH, BAND, FX] = process.argv.slice(2); const ADHOC = FX.startsWith("@") ? JSON.parse(fs.readFileSync(FX.slice(1), "utf8")) : null; const IDXS = ADHOC ? [] : FX.split(",").map(Number); const LR = process.env.LATERAL_RULE;
(async () => {
  const b = await puppeteer.launch({ executablePath: "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome", headless: "new", userDataDir: process.env.UDD || "chrome-layers", args: ["--no-sandbox"] });
  const p = await b.newPage(); await p.setViewport({ width: 1400, height: 900 });
  await p.goto("http://127.0.0.1:8124/sandbox/visual/match.html?gkBackend=3d" + (CH === "COURTOIS" ? "&gkChar=courtois" : "") + "&r=" + Date.now(), { waitUntil: "domcontentloaded", timeout: 180000 });
  for (let i = 0; i < 900; i++) { if (await p.evaluate((CH) => { const el = document.getElementById("loading"); const e = CH === "COURTOIS" ? GK_CHAR.get("COURTOIS") : null; return el && el.style.display === "none" && typeof ptEnter === "function" && (CH !== "COURTOIS" || (e && e.status === "ready")); }, CH)) break; await new Promise(r => setTimeout(r, 100)); }
  const res = await p.evaluate((CH, BAND, IDXS, ADHOC, LR) => { if (LR === "0") GK_GRAPH.lateralRule = false;
    if (!(S.pt && S.pt.on)) ptEnter(); GK_PRESENTATION.set("SKELETAL_3D"); if (CH === "COURTOIS") GL3D.character = "COURTOIS"; const r3 = v => Array.isArray(v) ? v.map(x => +(+x).toFixed(4)) : (v == null ? null : +(+v).toFixed(4)); const out = [];
    const fkOf = (skel, pose, rootM) => { const pel = skel.byName.pelvis, sv = pel.off.slice(); const pd = (pose && pose._pelvis) || [0, 0, 0]; pel.off = [sv[0] + pd[0], sv[1] + pd[1], sv[2] + pd[2]]; let fk; try { fk = skelFK(skel, pose, rootM); } finally { pel.off = sv; } return fk; };
    const J = (skel, fk, n) => r3(fk.joint[skel.byName[n].idx]); const upOf = (skel, fk, n) => { const m = fk.world[skel.byName[n].idx]; return r3(M4.transformDir(m, [0, 1, 0])); };
    const list = ADHOC ? ADHOC.map((sc, i) => ({ sc, idx: "adhoc" + i })) : IDXS.map(i => ({ sc: GK_SCENARIOS[i], idx: i }));
    for (const { sc, idx } of list) { S.pt.gkCap = BAND; ptReset(); if (ADHOC) { S.pt.gkScenario = null; ptGkFire(sc, 0, 1); } else ptGkScenario(idx); gkAnimResetView(); gk3dReset(); S.pt.paused = true; const rows = [];
      for (let k = 0; k < 200; k++) { ptStep(); updateRig(1 / 60, null); TRAVEL = RIG.x - 52.5; gkPresentationDraw(S.pt, S.pt.gk, 1 / 60); const L = GK3D.last; if (!L || !L.sol) continue; const g = L.g, sol = L.sol, d = sol.diag, desc = L.desc, gk = S.pt.gk, bl = S.pt.b, skel = GK3D.skel, h = g.reachHand || "R";
        const names = ["pelvis", "chest", "head", "thigh_R", "thigh_L", "shin_R", "shin_L", "foot_R", "foot_L", "upperArm_R", "upperArm_L", "foreArm_R", "foreArm_L", "hand_R", "hand_L"];
        const layer = (pose) => { if (!pose) return null; const fk = fkOf(skel, pose, g.rootM); const o = {}; for (const n of names) o[n] = J(skel, fk, n); o.chestUp = upOf(skel, fk, "chest"); o.tipHand = r3(fk.tip[skel.byName["hand_" + h].idx]); return o; };
        const fin = {}; for (const n of names) fin[n] = J(skel, sol.fk, n); fin.chestUp = upOf(skel, sol.fk, "chest"); fin.tipHand = r3(sol.fk.tip[skel.byName["hand_" + h].idx]);
        rows.push({ k, t: r3(S.pt.now), state: gk.state, phase: g.phase, sub: g.sub, mode: g.mode, motion: g.motion, u: r3(g.clipT), ikW: r3(g.ikW), side: g.side, hand: h,
          simRoot: r3([gk.x, gk.y]), simVel: r3([gk.vx, gk.vy]), simHand: r3(gk.handNow), ball: r3([bl.x, bl.y, bl.z]), contact: !!(gk.contact && Math.abs(gk.contact.tickT - S.pt.now) < 1e-3), committed: gk.committed ? { action: gk.committed.action, best: !!gk.committed.bestEffort, target: r3(gk.committed.target), t0: r3(gk.committed.t0), exec: r3(gk.committed.execTime), rootEnd: r3(gk.committed.rootEnd) } : null,
          pres: g.pres ? r3([g.pres.dx, g.pres.dy, g.pres.dm]) : null, axis: g.axis ? { theta: g.axis.theta, sign: g.axis.sign, wSide: r3(g.axis.wSide), pelvisOff: r3(g.axis.pelvisOff) } : null, launch: GK3D.state.launch ? { vUp: r3(GK3D.state.launch.vUp), vLat: r3(GK3D.state.launch.vLat), capped: !!GK3D.state.launch.capped, tT: r3(GK3D.state.launch.tT), tE: r3(GK3D.state.launch.tE), Pc: r3(GK3D.state.launch.Pc) } : null,
          rawPelvisOff: g.poseRaw ? r3(g.poseRaw._pelvis) : null, rawRoll: g.poseRaw && g.poseRaw.pelvis ? r3(g.poseRaw.pelvis) : null, redirPelvisOff: g.poseRedirected ? r3(g.poseRedirected._pelvis) : null, redirRoll: g.poseRedirected && g.poseRedirected.pelvis ? r3(g.poseRedirected.pelvis) : null, finalPelvisOff: r3(g.pose._pelvis), finalRoll: g.pose.pelvis ? r3(g.pose.pelvis) : null, wExt: r3(g.pose._wExt), wPos: r3(g.pose._wPos),
          raw: layer(g.poseRaw), redir: layer(g.poseRedirected), plan: layer(g.pose), final: fin, torso: r3(d.torso || 0), ground: r3(d.ground || 0), ik: d.ik ? { w: r3(d.ik.w), residual: r3(d.ik.residual), target: r3(d.ik.target), handCentre: r3(d.ik.handCentre) } : null, handTargetW: desc.handTarget ? r3(glW(desc.handTarget)) : null, flight: g.flight ? r3(g.flight.W) : null, landing: g.landing ? g.landing.L.stage : null }); }
      out.push({ idx, name: sc.name, band: S.pt.gkCap, H: GK3D.skel.H, rows }); }
    return out; }, CH, BAND, IDXS, ADHOC, LR);
  fs.writeFileSync(OUT, JSON.stringify(res)); console.log("layers", CH, BAND, res.length); await b.close(); })();
