import fs from "fs"; import zlib from "zlib";
const frozen = { "deepV": "d1g_PSTAR5CHABG_deep_V2-198-92_L_240", "diagV": "d1g_PSTAR5CHABG_diag_V2-198-92_L_180", "deep165V": "d1g_PSTAR5CHABG_deep_V2-165-62_L_180", "farV": "d1g_PSTAR5CHABG_far_V2-REF_L_240" };
for (const f of fs.readdirSync(".").filter(x => x.endsWith(".json.gz")).sort()) { const o = JSON.parse(zlib.gunzipSync(fs.readFileSync(f))), se = o.series, c = o.td2c, cl = se.closInc.map(Number), dt = 1 / o.hz;
  let best = { a: 0 }; for (const r of o.rows) { if (!r.L) continue; r.L.forEach((ax, j) => ax && ax.forEach((x, i) => { if (x && Math.abs(x.tau0) > best.a) best = { a: Math.abs(x.tau0), x }; })); }
  const G = c.gtr; let att = 0, attB = 0, prevW = null, prevT = null, prevCs = null; const lim = 30 * 240 / o.hz;
  for (const g of G) { const p = prevT != null && Math.abs(g.t - prevT - dt) < 1e-6 ? { w: prevW } : null, dw = Math.abs(g.w - (p ? p.w : 1)); if (dw > 0 && g.uax) for (const u of g.uax) { const v = dw * Math.abs(u[2] || u[3]); att = Math.max(att, v); if (v > lim) attB++; } prevW = g.w; prevT = g.t; }
  const modes = G.map(g => g.mode[0]).join(""), runs = modes.match(/F+/g) || [];
  const tLo = o.events.tLo, seg = (a, b) => cl.reduce((s2, v, k) => s2 + (se.t[k] >= a && se.t[k] < b ? Math.max(0, v) : 0), 0);
  console.log(f.padEnd(18), "cmdMax", Math.max(...se.cmdMax).toFixed(0), "dom", best.x ? Object.entries({ st: best.x.statics, d1: best.x.d1, kp: best.x.kp, vff: best.x.vffServo }).sort((p2, q) => Math.abs(q[1]) - Math.abs(p2[1]))[0].map(v => typeof v === "number" ? v.toFixed(0) : v).join(" ") : "", "| dTau0", Math.max(...se.dTau0).toFixed(0), "| clos", Math.max(...cl).toFixed(4), "Σ+", cl.reduce((s2, v) => s2 + Math.max(0, v), 0).toFixed(3), tLo != null ? `[sw ${seg(tLo, tLo + 0.6).toFixed(3)} hold ${seg(tLo + 0.6, 99).toFixed(3)}]` : "", "| invalid", c.d1g.invalid, "| guard step max", att.toFixed(2), "(>", lim, ":", attB, ") | fades", runs.length, "max len", Math.max(0, ...runs.map(x => x.length)), "| overCap", o.integrity.overCap, "fell", c.fell); }
