import fs from "fs"; import { walk, f3, fallT } from "./lib.mjs"; import { failReport } from "./failan.mjs";
const J = (p) => JSON.parse(fs.readFileSync("/Users/zainrahman/Downloads/FC Simulator worktrees/physical-character-v1/review_artifacts/physical_character_v1/g2_walker/json/" + p, "utf8"));
const a = JSON.parse(process.argv[2] || "{}"), pre = a.models || "model1_tau", models = {}; for (const t of [0, 0.1, 0.15, 0.2, 0.25]) models[t] = J(`${pre}${t}.json`);
const ctrl = { kind: "A", models, nom: a.nom || [0.32, 0.22, 0.38], rho: a.rho ?? 0.4, sig: [0.05, 0.05, 0.03], lo: [0.10, 0.17, 0.36], hi: [a.dfMax ?? 0.48, 0.40, 0.48], inSwing: a.inSwing ?? 0.25, adapt: a.adapt };
const n = a.n ?? 16, r = walk({ n, keep: true, seconds: 1.6 + n * 0.58, walk: { dsLead: true, dsFlat: false, dsExtEnd: 0.96, ...(a.inner || {}), char: { 0: { df: a.fdf ?? 0.24, dl: a.fdl ?? 0.351, T: a.fT ?? 0.448 } }, ctrl }, human: { lateBlend: true, clrActual: true, clrActualUntil: [0.5, 0.2] } });
const R = failReport(r), log = r.LOCO.planner.rhythm.walkerLog;
for (const e of log) { const s = R.steps.find(q => q.k === e.i), s1 = R.steps.find(q => q.k === e.i + 1), last = e.adj.length ? e.adj[e.adj.length - 1] : null;
  console.log(`k${e.i}${e.sw} x ${e.x.map(v => f3(v)).join(",")} | start u ${e.u.map(v => f3(v)).join(",")} pred ${e.info.pred.map(v => f3(v)).join(",")} | last adj τ${last ? f3(last.tau, 2) : "-"} x(τ) ${last ? last.x.map(v => f3(v)).join(",") : "-"} u ${last ? f3(last.df) + "," + f3(last.dl) : "-"} pred ${last && last.pred ? last.pred.map(v => f3(v)).join(",") : "-"} | achieved ${s && s.ach ? s.ach.map(v => f3(v)).join(",") : "-"} swing ${s ? f3(s.swing, 2) : "-"} | ACTUAL next x ${s1 ? s1.xi.map(v => f3(v)).join(",") : "-"} vL ${s1 ? f3(s1.vL, 2) : "-"} ext ${s1 ? f3(s1.trailExt, 2) : "-"}`); }
if (R.fall) console.log(`fall ${f3(R.fall.t, 2)} dir fwd ${f3(R.fall.dirF, 2)} right ${f3(R.fall.dirR, 2)}`);
const P = r.LOCO.planner, h0 = P.rhythm.wk.h0, hd = [Math.sin(h0), Math.cos(h0)], rt = [hd[1], -hd[0]];
const pr = (c, ps, sd) => c ? [(c[0] - ps[0]) * hd[0] + (c[1] - ps[1]) * hd[1], ((c[0] - ps[0]) * rt[0] + (c[1] - ps[1]) * rt[1]) * sd].map(v => f3(v)).join(",") : "-";
for (const d of P.exec.done.filter(d => d.kind === "rhythmic")) { const sd = d.sw === "R" ? 1 : -1; console.log(`k${d.stepIndex} nominalTarget ${pr(d.nominalTarget, d.pSt, sd)} proj.target ${pr(d.proj && d.proj.target, d.pSt, sd)} landC ${pr(d.landC, d.pSt, sd)} plannedTd ${pr(d.plannedTd && d.plannedTd.center, d.pSt, sd)} td ${pr(d.td && d.td.center, d.pSt, sd)} adjusted ${d.adjusted || 0} T ${f3(d.T, 3)} tSw ${f3(d.tSw0, 3)} td.t ${d.td ? f3(d.td.t, 3) : "-"} uAt ${d.td ? f3(d.td.uAt, 2) : "-"}`); }
{ const K = +(a.trace ?? 2), d = P.exec.done.find(d => d.kind === "rhythmic" && d.stepIndex === K), sd = d.sw === "R" ? 1 : -1, fb = (await import("./lib.mjs")).bi("foot_" + d.sw), M2 = (await import("./lib.mjs")).M, box = (await import("./lib.mjs")).spec.bodies[fb].shapes[0];
  console.log(`--- step ${K} swing: target vs foot centre (forward from stance point)`);
  for (const q of r.recs.filter(q => q.t >= d.tSw0 && q.t <= (d.td ? d.td.t : d.tSw0 + 0.5) + 0.02 && Math.round(q.t * 240) % 6 === 0)) { const S = q.states[fb], c = M2.V.add(S.pos, M2.Q.rot(S.rot, box.pos)), tg = q.swingTgt;
    const tgc = tg && tg.pos ? M2.V.add(tg.pos, M2.Q.rot(tg.rot, box.pos)) : null, fw = (p) => p ? f3((p[0] - d.pSt[0]) * hd[0] + (p[2] - d.pSt[1]) * hd[1]) : "-";
    console.log(`t ${f3(q.t, 3)} ${q.exec ? q.exec.stage + " u" + f3(q.exec.u, 2) : "-"} target ${fw(tgc)} foot ${fw(c)} footV ${f3(S.v[0] * hd[0] + S.v[2] * hd[1], 2)} footY ${f3(S.pos[1], 3)} load ${f3(q.feet[d.sw].load, 0)}`); } }
