// TD2 design study: the AB baseline's contact-window load split (first 12 ms vs later), the load / speed bound per rate, the resting lowest-point spread, and the
// load-peak mechanism of one case (V2-198-92 L 240 H-D). Input: the frozen FB battery's PSTAR5CHAB records. usage: node ab_touchdown_profile.mjs <runs dir>
import fs from "fs"; import zlib from "zlib";
const D = process.argv[2], res = {}, rest = [], landed = []; const q = (a, p) => { const b = a.slice().sort((x, y) => x - y); return b[Math.floor(p * (b.length - 1))]; };
for (const f of fs.readdirSync(D).filter(x => x.startsWith("fb_PSTAR5CHAB_") && x.endsWith(".json.gz"))) { const r = JSON.parse(zlib.gunzipSync(fs.readFileSync(D + "/" + f))), R = r.rows, W = r.W, dt = 1 / r.hz, i1 = R.findIndex(x => x.t === r.t1); if (i1 < 1) continue;
  const win = R.slice(i1).filter(x => x.t <= r.t1 + 0.1 + 1e-9), pI = Math.max(...win.filter(x => x.t <= r.t1 + 0.012 + 1e-9).map(x => x.Fz)) / W, pk = Math.max(...win.map(x => x.Fz)) / W, v = R[i1 - 1].pc.vN, vT = R[i1 - 1].pc.vT;
  const wmax = Math.max(...R.slice(i1, i1 + Math.round(0.03 / dt)).map(x => Math.hypot(...x.wF))); (res[r.hz] = res[r.hz] || []).push({ pI, pk, v, vT, wmax, tr: f.split("_").slice(-1)[0].replace(".json.gz", "") });
  if (r.lowRest != null) { rest.push(r.lowRest); const s = (r.post || []).find(x => r.tSup != null && x.t >= r.tSup - 1e-9); if (s) landed.push(s.low); } }
for (const hz of [180, 240, 480]) { const S = res[hz], n = S.length, corr = (a, b) => { const ma = a.reduce((s, x) => s + x, 0) / n, mb = b.reduce((s, x) => s + x, 0) / n; return a.reduce((s, x, i) => s + (x - ma) * (b[i] - mb), 0) / Math.sqrt(a.reduce((s, x) => s + (x - ma) ** 2, 0) * b.reduce((s, x) => s + (x - mb) ** 2, 0)); };
  console.log(`${hz} Hz (n ${n}): load peak in [t1, t1+100 ms] %BW median ${(100 * q(S.map(s => s.pk), 0.5)).toFixed(1)} max ${(100 * Math.max(...S.map(s => s.pk))).toFixed(1)} | first 12 ms median ${(100 * q(S.map(s => s.pI), 0.5)).toFixed(1)} max ${(100 * Math.max(...S.map(s => s.pI))).toFixed(1)} | max peak/v ${Math.max(...S.map(s => s.pk / s.v)).toFixed(2)} BW per m/s → v(25 %) ${(250 / Math.max(...S.map(s => s.pk / s.v))).toFixed(1)} mm/s | corr(peak, v) ${corr(S.map(s => s.pk), S.map(s => s.v)).toFixed(2)} corr(peak, pivot ω) ${corr(S.map(s => s.pk), S.map(s => s.wmax)).toFixed(2)}`);
  for (const set of ["R", "C", "H"]) { const T = S.filter(s => s.tr[0] === set); console.log(`   ${set}: contact-point downward speed median ${(1000 * q(T.map(s => s.v), 0.5)).toFixed(0)} max ${(1000 * Math.max(...T.map(s => s.v))).toFixed(0)} mm/s; tangential median ${(1000 * q(T.map(s => s.vT), 0.5)).toFixed(0)} max ${(1000 * Math.max(...T.map(s => s.vT))).toFixed(0)} mm/s`); } }
console.log(`resting lowest boot point (mm): anchor min ${Math.min(...rest).toFixed(3)} max ${Math.max(...rest).toFixed(3)}; landed at first SUPPORT min ${Math.min(...landed).toFixed(3)} max ${Math.max(...landed).toFixed(3)}`);
{ const r = JSON.parse(zlib.gunzipSync(fs.readFileSync(D + "/fb_PSTAR5CHAB_V2-198-92_L_240_H-D.json.gz"))), R = r.rows, i1 = R.findIndex(x => x.t === r.t1); console.log("mechanism, V2-198-92 L 240 H-D (tick from the first touching tick: state, touching pieces, load %BW, foot |ω| rad/s, tilt °):");
  for (let i = i1 - 1; i < i1 + 8; i++) { const x = R[i]; console.log(`   ${i - i1} ${x.st} ${x.touch} ${(100 * x.Fz / r.W).toFixed(1)} ${Math.hypot(...x.wF).toFixed(3)} ${x.tiltErr.toFixed(2)}`); } }
