// TD2 design qualification of the NEW trajectory region (Decision 4; windows relative to the record's own TD2 parameters: approach φ, the settling dwell [T, T + τ_d), the search): the band-top approach + search with the turf 10 mm below the commanded foothold (no contact before escalation),
// all bodies × legs × rates × trajectories. Per run: (1) downward deviation of the actual lowest boot point from the reference pose's (lowRef − low, mm; both conventions: same row and
// the reference one tick later) in φ ∈ [0.75, 0.9), [0.9, 1.0) and during the search (u ∈ [T, T + τ_s]); (2) upward deviation (low − lowRef) in the same windows; (3) the potential-
// contact sole points' tangential speed and the foot origin's horizontal speed at T and after it (the time after T after which they stay ≤ v); (4) foot angular speed after T;
// (5) the actual lowest point's downward speed during the search. usage: node hover_qualification.mjs <runs dir>
import fs from "fs"; import zlib from "zlib";
const D = process.argv[2], L = (a) => Math.hypot(...a), q = (a, p) => { const b = a.slice().sort((x, y) => x - y); return b[Math.min(b.length - 1, Math.floor(p * (b.length - 1)))]; };
const runs = []; for (const f of fs.readdirSync(D).filter(x => x.endsWith(".json.gz"))) { const r = JSON.parse(zlib.gunzipSync(fs.readFileSync(D + "/" + f))), R = r.rows, T = r.tr.T, tLo = r.events.tLo, dt = 1 / r.hz, tr = f.split("_").slice(-1)[0].replace(".json.gz", "");
  if (tLo == null) continue; const PP = r.td2.params || {}, tauS = PP.tauS ?? 0.150, tauD = PP.tauD ?? 0, tEsc = r.td2.failedTD ?? Infinity, pre = R.filter(x => x.u != null && x.t < tEsc - 1e-9 && x.ph === "swing");
  const win = (a, b) => pre.filter(x => x.u / T >= a - 1e-9 && x.u / T < b - 1e-9), dwell = pre.filter(x => x.u >= T - 1e-9 && x.u < T + tauD - 1e-9), srch = pre.filter(x => x.u >= T + tauD - 1e-9 && x.u <= T + tauD + tauS + 1e-9), hold = pre.filter(x => x.u > T + tauD + tauS + 1e-9);
  const dn = (S) => { let m = -Infinity; S.forEach(x => { const i = R.indexOf(x), z = R[i + 1]; m = Math.max(m, x.lowRef - x.low, z && z.lowRef != null ? z.lowRef - x.low : -Infinity); }); return m; }, upd = (S) => Math.max(...S.map(x => x.low - x.lowRef));
  const after = pre.filter(x => x.u >= T + tauD - 1e-9), settle = (key, v) => { let tl = 0; for (const x of after) if (key(x) > v) tl = x.u - T + dt; return tl; };
  const vT = (x) => x.pc.vT, vF = (x) => Math.hypot(x.foot.v[0], x.foot.v[2]), wF = (x) => L(x.wF);
  const lowV = []; for (let i = 1; i < srch.length; i++) if (Math.abs(srch[i].t - srch[i - 1].t - dt) < 1e-6) lowV.push(-(srch[i].low - srch[i - 1].low) / dt);
  runs.push({ f: f.slice(2, -8), tr, hz: r.hz, d75: dn(win(0.75, 0.9)), d90: dn(win(0.9, 1.0)), dD: dwell.length ? dn(dwell) : null, dS: srch.length ? dn(srch) : null, dH: hold.length ? dn(hold) : null, u75: upd(win(0.75, 1.0)), uS: srch.length ? upd(srch) : null,
    vT0: after.length ? vT(after[0]) : null, vF0: after.length ? vF(after[0]) : null, sT50: settle(vT, 0.05), sT25: settle(vT, 0.025), sF50: settle(vF, 0.05), sF25: settle(vF, 0.025), w0: after.length ? wF(after[0]) : null, sW: settle(wF, 0.05), lowVmax: lowV.length ? Math.max(...lowV) : null, esc: r.td2.failedTD != null, tdBefore: r.trans.some(x => x.n === r.swing && x.to === "TOUCHDOWN" && x.t > tLo && x.t < tEsc) }); }
console.log(`runs ${runs.length}; escalated ${runs.filter(r => r.esc).length}; swing-foot TOUCHDOWN before escalation ${runs.filter(r => r.tdBefore).length}`);
const rep = (S, tag) => { const M = (k) => Math.max(...S.map(r => r[k]).filter(v => v != null)), P = (k, p) => q(S.map(r => r[k]).filter(v => v != null), p);
  console.log(`${tag.padEnd(8)} n ${String(S.length).padStart(3)} | downward dev (mm) φ.75–.9 max ${M("d75").toFixed(2)} | φ.9–1 max ${M("d90").toFixed(2)} (p95 ${P("d90", 0.95).toFixed(2)}) | dwell max ${S.some(r => r.dD != null) ? M("dD").toFixed(2) : "—"} | search max ${M("dS").toFixed(2)} | hold max ${M("dH").toFixed(2)} | upward φ≥.75 max ${M("u75").toFixed(2)}, search ${M("uS").toFixed(2)}`
    + ` | tangential at the search start: pc ${M("vT0") * 1000 | 0} foot ${M("vF0") * 1000 | 0} mm/s; settle after the search start to ≤50 / ≤25 mm/s (max): pc ${(M("sT50") * 1000).toFixed(0)} / ${(M("sT25") * 1000).toFixed(0)} ms, foot ${(M("sF50") * 1000).toFixed(0)} / ${(M("sF25") * 1000).toFixed(0)} ms | |ω| at T max ${M("w0").toFixed(3)} settle ≤0.05 ${(M("sW") * 1000).toFixed(0)} ms | lowest-point downward speed in search max ${M("lowVmax").toFixed(1)} mm/s`); };
rep(runs, "ALL"); for (const s of ["R", "C", "H"]) rep(runs.filter(r => r.tr[0] === s), "set " + s); for (const hz of [180, 240, 480]) rep(runs.filter(r => r.hz === hz), hz + " Hz");
for (const tr of ["R-F", "R-L", "C-F7", "C-F13", "C-L5", "H-T45", "H-A40", "H-D", "H-F15"]) rep(runs.filter(r => r.tr === tr), tr);
const worst = runs.slice().sort((a, b) => Math.max(b.d90, b.dD ?? 0, b.dS ?? 0) - Math.max(a.d90, a.dD ?? 0, a.dS ?? 0)).slice(0, 6); console.log("worst downward deviation runs:", worst.map(r => `${r.f} ${Math.max(r.d90, r.dD ?? 0, r.dS ?? 0).toFixed(2)}`).join(", "));
fs.writeFileSync(process.argv[3] || "/dev/null", JSON.stringify(runs));
