// LC-1 results tables (text) from the official outputs in <dir> (scratch lc/): fine-rate (LC-1a / LC-2 / LC-6c), 60 Hz criteria, valid frames, coherence.
import fs from "fs"; const D = process.argv[2], J = (f) => JSON.parse(fs.readFileSync(D + "/" + f));
const speeds = ["1.45", "2.2", "3", "4.2", "5.5", "6.5", "7.5", "8.2"], P = (b) => (b == null ? "–" : b ? "pass" : "FAIL");
console.log("== fine-rate construction (3840 Hz), worst per-step velocity change (m/s); limit 0.18");
console.log("run | pelvis on/off | COM on/off | worst joint on (bone) / off | joint steps over limit on | LC-6c");
for (const r of speeds.concat(["ramp"])) { const on = J(`fine/on_${r}.json`).runs[r], off = J(`fine/off_${r}.json`).runs[r];
  console.log(`${r} | ${on.LC1a.pelvis.max} / ${off.LC1a.pelvis.max} | ${on.LC1a.com.max} / ${off.LC1a.com.max} | ${on.LC2.worst.max} (${on.LC2.worst.bone}) / ${off.LC2.worst.max} | ${on.LC2.jointStepsOver} of ${on.steps * 22} | ${on.LC6c.identical && off.LC6c.identical}`); }
for (const [lab, a, b] of [["speed fixtures", "eval_on_speed.json", "eval_off_speed.json"]]) { const A = J(a).records, B = J(b).records;
  console.log(`\n== 60 Hz criteria, ${lab} (LC-1 / V1.3)`); console.log("speed | 1b COM v h,v max | 3 slip max mm | 4a flight resid mm | 4b F min..max | 4c | 5a | 5c mm | legVsSim p50 mm | contact agree");
  for (const k of Object.keys(A)) { const r = A[k], o = B[k.replace("on/", "off/")]; if (!o) continue;
    console.log(`${r.speed} | ${r.LC1b.h.max},${r.LC1b.v.max} ${P(r.LC1b.pass)} / ${o.LC1b.h.max},${o.LC1b.v.max} | ${r.LC3.maxMm} ${P(r.LC3.pass)} / – | ${r.LC4a.maxResidMm} ${P(r.LC4a.pass)} / ${o.LC4a.maxResidMm} | ${r.LC4b.F.min}..${r.LC4b.F.max} ${P(r.LC4b.pass)} / ${o.LC4b.F.min}..${o.LC4b.F.max} | ${r.LC4c.maxMs} / ${o.LC4c.maxMs} | ${r.LC5a.e.max} / ${o.LC5a.e.max} | ${r.LC5c.maxDispMm} / ${o.LC5c.maxDispMm} | ${r.reported.legVsSimMm.p50} / ${o.reported.legVsSimMm.p50} | ${r.reported.contactAgreement} / ${o.reported.contactAgreement}`); } }
console.log("\n== valid promotion frames, speed fixtures (of 228): LC-1 / V1.3");
const vo = J("valid_on_speed.json"), vf = J("valid_off_speed.json"); for (const s of speeds) { const k = "lc_v" + s; console.log(`${s}: ${vo[k].valid.length} / ${vf[k].valid.length}`); }
console.log("\n== coherence of promoted unobstructed runners (speed fixtures, LC-1, all valid frames, horizon 30 ticks)"); const C = J("coh_on_speed.json"); for (const [k, c] of Object.entries(C)) console.log(`${k}: runs ${c.runs}, coherent p50/p90/max ${c.coherentTicks.p50}/${c.coherentTicks.p90}/${c.coherentTicks.max}, through ${c.throughHorizon}, first fail ${JSON.stringify(c.firstFail)}, PR-2 v2 p50 ${c.PR2v2.p50} (min ${c.PR2v2.min}) pass ${c.PR2v2.pass}/${c.PR2v2.of}`);
console.log("\n== PI-1 records, 60 Hz criteria pass counts (LC-1 / V1.3)"); const ER = Object.assign({}, J("eval_on_rx.json").records, J("eval_on_def.json").records), EO = Object.assign({}, J("eval_off_rx.json").records, J("eval_off_def.json").records);
for (const row of ["LC1b", "LC3", "LC4a", "LC4b", "LC4c", "LC5a", "LC5b", "LC5c"]) { const cnt = (E) => { let p = 0, n = 0; for (const r of Object.values(E)) { const v = r[row].pass; if (v == null) continue; n++; if (v) p++; } return `${p}/${n}`; }; console.log(`${row}: ${cnt(ER)} / ${cnt(EO)}`); }
console.log("\n== PI-1 records, valid frames in the pre-contact window (LC-1 / V1.3)"); const VR = Object.assign({}, J("valid_on_rx.json"), J("valid_on_def.json")), VO = Object.assign({}, J("valid_off_rx.json"), J("valid_off_def.json"));
for (const k of Object.keys(VR)) console.log(`${k} (${VR[k].speed.toFixed(1)} m/s): ${VR[k].valid.length} / ${VO[k] ? VO[k].valid.length : "–"}; latest lead ${VR[k].valid.length ? VR[k].valid.filter(x => x.lead != null).map(x => x.lead).sort((a, b) => a - b)[0] : "–"} / ${VO[k] && VO[k].valid.length ? VO[k].valid.filter(x => x.lead != null).map(x => x.lead).sort((a, b) => a - b)[0] : "–"}`);
