#!/bin/zsh
# DVG COMBINED QUALIFICATION (e2/DVG_PREREG.md §4): the frozen e2/CQ_RUN_LIST.json — CQ-2 reach stress 432 (tools/dvg_val.mjs: guard off / DVG / R0), CQ-4 (a) repeats 24, CQ-3 (a) mirror
# probes 24 (tools/dvg_unit.mjs), CQ-1 (a) AB nominal 432 (td2b_val via dvg_wrap), (b) SV-2 servo-on 438 (swing_servo_val2 via dvg_wrap), (c) E1a 10 + E1b 28 PSTAR4 with DVG injected and
# with DVG off; CQ-0 identity (scripts/dvg_identity.sh). Evaluated by tools/dvg_eval.mjs. Clean copy of the COMMITTED tree; refuses with uncommitted changes under sandbox/visual/physchar2.
W="/Users/zainrahman/Downloads/FC Simulator worktrees/physical-character-v2"; S=/private/tmp/claude-501/-Users-zainrahman/8af3fa3f-f134-4178-b7ae-7855027dda6e/scratchpad
C=$S/dvgcq/run; T=$C/tree; P=$T/sandbox/visual/physchar2; RA="$W/review_artifacts/physical_character_v2"; EV="$RA/e2/evidence_dvg"; log() { echo "$(date +%H:%M:%S) $*" | tee -a $C/queue.log; }
mkdir -p $C/{runs,rep,unit,ab,sv2,jobs,id} $C/e1/on/A $C/e1/on/E $C/e1/off/A $C/e1/off/E $T "$EV"
[ -z "$(cd "$W" && git status --porcelain sandbox/visual/physchar2)" ] || { echo "uncommitted changes under sandbox/visual/physchar2 — refusing"; exit 1; }
(cd "$W" && git rev-parse HEAD > $C/commit.txt && git status --short > $C/tree_status.txt); (cd "$W" && git archive HEAD sandbox/visual/physchar2) | tar -x -C $T
unset V2_KNEE_MODEL V2_KNEE_V2K V2_ANKLE_NEUTRAL_K V2_KNEE_ENVELOPE V2_XSTAND V2_KNEE_CRIT B_TURF
cp "$RA/e2/CQ_RUN_LIST.json" $C/list.json; log "start (commit $(cat $C/commit.txt))"
(cd $P && bash "$RA/e2/scripts/dvg_identity.sh" $C/id > $C/id/identity.out 2>&1); log "CQ-0 identity: $(grep -c '^PASS' $C/id/summary.txt) PASS lines; $(head -1 $C/id/summary.txt)"
node -e 'const fs=require("fs"), L=JSON.parse(fs.readFileSync(process.argv[1])); const [P,C]=process.argv.slice(2); let n=0; const job=(cmd)=>{ n++; fs.writeFileSync(`${C}/jobs/j${String(n).padStart(4,"0")}.sh`, `#!/bin/zsh\ncd "${P}"\nexport V2_KNEE_MODEL=v2k V2_ANKLE_NEUTRAL_K=0.13\n${cmd}\n`); };
  for (const q of L.stress) { const f=`dvg_${q.cfg}_${q.cond}_${q.body}_${q.side}_${q.hz}`; job(`node tools/dvg_val.mjs --human=${q.body} --side=${q.side} --hz=${q.hz} --cfg=${q.cfg} --cond=${q.cond} --out=${C}/runs/${f}.json.gz > ${C}/runs/${f}.log 2>&1`); }
  for (const q of L.rep) { const f=`dvg_${q.cfg}_${q.cond}_${q.body}_${q.side}_${q.hz}`; job(`node tools/dvg_val.mjs --human=${q.body} --side=${q.side} --hz=${q.hz} --cfg=${q.cfg} --cond=${q.cond} --out=${C}/rep/${f}.json.gz > ${C}/rep/${f}.log 2>&1`); }
  for (const q of L.unit) { const f=`dvgu_${q.body}_${q.cond}`; job(`node tools/dvg_unit.mjs --human=${q.body} --cond=${q.cond} --out=${C}/unit/${f}.json.gz > ${C}/unit/${f}.log 2>&1`); }
  for (const q of L.ab) { const f=`ab_${q.body}_${q.side}_${q.hz}_${q.traj}`; job(`node tools/dvg_wrap.mjs --dvgcfg=PSTAR5CHAB --dvglog=${C}/ab/${f}.dvg.json.gz tools/td2b_val.mjs --human=${q.body} --side=${q.side} --hz=${q.hz} --cfg=PSTAR5CHAB --traj=${q.traj} --cond=nominal --out=${C}/ab/${f}.json.gz > ${C}/ab/${f}.log 2>&1`); }
  for (const q of L.sv2) { const f=`${q.body}_${q.side}_${q.hz}_on_${q.traj}`; job(`node tools/dvg_wrap.mjs --dvgcfg=PSTAR5CH --dvglog=${C}/sv2/sv2g_${f}.dvg.json.gz tools/swing_servo_val2.mjs --human=${q.body} --side=${q.side} --hz=${q.hz} --ff=on --traj=${q.traj} --out=${C}/sv2/sv2_${f}.json.gz > ${C}/sv2/sv2g_${f}.log 2>&1`); }
  for (const q of L.e1a) { const f=`e1a_${q.body}_${q.side}${q.rep?"_rep":""}`, a=`--config=PSTAR4 --human=${q.body} --side=${q.side}`;
    job(`node tools/dvg_wrap.mjs --dvginject --dvglog=${C}/e1/on/${f}.dvg.json.gz tools/e1a_run.mjs ${a} --out=${C}/e1/on/A/${f}.json.gz > ${C}/e1/on/${f}.log 2>&1`); job(`node tools/e1a_run.mjs ${a} --out=${C}/e1/off/A/${f}.json.gz > ${C}/e1/off/${f}.log 2>&1`); }
  for (const q of L.e1b) { const f=`e1b_${q.body}_${q.side}_${q.pert}`, a=`--config=PSTAR4 --human=${q.body} --side=${q.side} --pert=${q.pert}`;
    job(`node tools/dvg_wrap.mjs --dvginject --dvglog=${C}/e1/on/${f}.dvg.json.gz tools/e1b_run.mjs ${a} --out=${C}/e1/on/E/${f}.json.gz > ${C}/e1/on/${f}.log 2>&1`); job(`node tools/e1b_run.mjs ${a} --out=${C}/e1/off/E/${f}.json.gz > ${C}/e1/off/${f}.log 2>&1`); }
  console.log(n);' $C/list.json $P $C > $C/njobs.txt
log "jobs: $(cat $C/njobs.txt)"; ls $C/jobs/*.sh | xargs -P 8 -n 1 zsh; log "runs done: stress $(ls $C/runs/*.json.gz | wc -l) rep $(ls $C/rep/*.json.gz | wc -l) unit $(ls $C/unit/*.json.gz | wc -l) ab $(ls $C/ab/*.log | wc -l) sv2 $(ls $C/sv2/*.log | wc -l) e1 on $(ls $C/e1/on/*.log | wc -l) off $(ls $C/e1/off/*.log | wc -l)"
mkdir -p $C/td2blogs && tar -xzf "$RA/e2/evidence_td2b/logs/run_logs.tgz" -C $C/td2blogs
EA=(--list=$C/list.json --dir=$C/runs --rep=$C/rep --unit=$C/unit --ab=$C/ab --td2blogs=$C/td2blogs --sv2=$C/sv2 --sv2logs="$RA/e2/evidence_sv2/logs" --e1=$C/e1 --identity=$C/id/summary.txt --fbjson="$RA/e2/evidence_fb/fb_eval.json.gz")
if grep -L "invalid 0$" $C/sv2/sv2g_*.log | grep -q .; then (cd $P && node tools/swing_servo_eval2.mjs --dir=$C/sv2 --list="$RA/e2/evidence_sv2/list.json" --json=$C/sv2_eval_guarded.json > $C/sv2_eval_guarded.txt 2>&1); EA+=(--sv2evalNew=$C/sv2_eval_guarded.json --sv2eval="$RA/e2/evidence_sv2/sv2_eval.json"); log "SV-2 engaged runs: frozen SV-2 evaluator on the guarded records"; fi
if grep -L "invalid 0$" $C/e1/on/*.log | grep -q .; then mkdir -p $C/e1/evalOn $C/e1/evalOff; for s in on off; do (cd $P && node tools/e1a_eval.mjs --dir=$C/e1/$s/A --config=PSTAR4 --out=$C/e1/eval${(C)s}/e1a_eval.json > $C/e1/eval${(C)s}/e1a_eval.log 2>&1; node tools/e1b_eval.mjs --dir=$C/e1/$s/E --config=PSTAR4 --out=$C/e1/eval${(C)s}/e1b_eval.json > $C/e1/eval${(C)s}/e1b_eval.log 2>&1); done; EA+=(--e1evalOn=$C/e1/evalOn --e1evalOff=$C/e1/evalOff); log "E1 engaged runs: frozen E1a / E1b evaluators on both sets"; fi
(cd $P && node tools/dvg_eval.mjs $EA --json=$C/dvg_eval.json > $C/dvg_eval_summary.txt 2>&1); log "EVAL: $(tail -1 $C/dvg_eval_summary.txt)"
mkdir -p "$EV/logs" "$EV/records" "$EV/unit" "$EV/identity"; (cd $C && tar -czf "$EV/logs/run_logs.tgz" runs/*.log rep/*.log unit/*.log ab/*.log sv2/*.log e1/on/*.log e1/off/*.log) ; (cd $C && tar -czf "$EV/logs/guard_traces.tgz" ab/*.dvg.json.gz sv2/*.dvg.json.gz e1/on/*.dvg.json.gz 2>/dev/null)
cp $C/runs/*.json.gz "$EV/records/"; cp $C/unit/*.json.gz "$EV/unit/"; cp $C/id/summary.txt $C/id/*.verdict "$EV/identity/" 2>/dev/null
gzip -c $C/dvg_eval.json > "$EV/dvg_eval.json.gz"; for f in commit.txt tree_status.txt queue.log list.json dvg_eval_summary.txt sv2_eval_guarded.txt; do cp $C/$f "$EV/" 2>/dev/null; done; [ -d $C/e1/evalOn ] && cp -r $C/e1/evalOn $C/e1/evalOff "$EV/"; log "ALL DONE"; touch $C/all.done
