// ── D6 DIAGNOSTIC (D6_slide + the D6X matrix): the struck player's causal chain — live from pc_d6diag (the same measurement code as
// tools/d6x_run.js), plus the Node matrix JSON for the instrumented twin's EXACT contact force / momentum ledger (JoltPhysics.js exposes no
// contact impulses; see pc_d6diag.js) ──────────────────────────────────────────────────────────────────────────────────────────────
const d6Node = (k) => H.d6x && H.d6x.results ? H.d6x.results.find(q => q.test === k) : null;
const d6Force = (t) => { const n = d6Node(H.testD), s = n && n.forceSeries; if (!s) return null; const i = Math.round((t - s.t0) / s.dt); return i >= 0 && i < s.F.length ? { F: s.F[i], turf: s.turf[i] } : null; };
function drawD6(d, labels) { const O = H.ov, b = d.B, c = b.com, cg = [c[0], 0.004, c[2]], hs = (v) => Math.hypot(v[0], v[2]);
  if (O.c_region && b.region && b.region.length >= 3) { polyLine(b.region, [0.3, 1, 0.5, 1]);
    labels.push([G2(b.region[0], 0.01), `B support region · ξ margin ${b.xiM > -999 ? (b.xiM * 100).toFixed(1) + " cm" : "— (no support polygon)"}`, b.xiM > 0.015 ? "#8cf0a0" : b.xiM > -0.05 ? "#ffd070" : "#ff7070"]); }
  if (O.c_com) { cross3(cg, 0.03, [1, 0.35, 0.9, 1]); L(c, cg, [1, 0.35, 0.9, 0.5]); L(c, V.add(c, V.sc(b.vcom, 0.5)), [1, 0.5, 1, 1]); if (hs(b.vcom) > 0.03) labels.push([V.add(c, V.sc(b.vcom, 0.5)), `B COM ${hs(b.vcom).toFixed(2)} m/s`, "#ff90ff"]); }
  if (O.c_xi) { const x = [b.xi[0], 0.006, b.xi[1]]; ring(x, 0.035, [0.2, 1, 1, 1]); L(cg, x, [0.2, 1, 1, 0.8]); labels.push([x, "ξ", "#60ffff"]); }
  if (O.c_cop) { if (b.cop) cross3([b.cop[0], 0.008, b.cop[1]], 0.03, [1, 1, 1, 1]); if (b.pStar) ring([b.pStar[0], 0.01, b.pStar[1]], 0.02, [0.3, 0.7, 1, 1]); }
  if (O.c_feet) for (const s of ["L", "R"]) { const f = b.feet[s], col = FOOT_COL[f.st] || [1, 1, 1, 1], base = [f.pos[0], f.pos[1] + 0.12, f.pos[2]], top = V.add(base, [0, Math.max(0, f.load) / 800 * 0.4, 0]);
    if (f.sole) polyLine([0, 1, 3, 2].map(q => f.sole[q]), [col[0], col[1], col[2], 0.8], 0.003); L(base, top, col);
    labels.push([V.add(top, [0, 0.02, 0]), `${s === "L" ? "struck L" : "far R"} ${f.st} ${f.load.toFixed(0)} N${f.slip ? " · SLIP" : ""}`, f.slip ? "#ff6060" : "#c8f0c8"]); }
  if (O.impulse && d.pairs.length) { const fz = d6Force(d.t), F = fz && fz.F, len = F ? Math.hypot(...F) : 0;
    for (const p of d.pairs.slice(0, 3)) { const dir = F && len > 1 ? V.sc(F, 1 / len) : p.n, sc = F ? Math.min(0.6, len * 0.00025) : 0.12; L(V.sub(p.p, V.sc(dir, sc)), p.p, [1, 0.25, 0.25, 1]); cross3(p.p, 0.02, [1, 0.25, 0.25, 1]); }
    labels.push([d.pairs[0].p, `${d.pairs[0].a} → ${d.pairs[0].b} @ ${d.pairs[0].y.toFixed(2)} m${F ? ` · A→B ${hs(F).toFixed(0)} N horiz. (twin)` : ""}`, "#ff8080"]); } }
// chart 2 (D6): contact force A→B and turf→B (twin, exact) · foot loads (struck L / far R; slip and air shaded) · ξ margin + classification band
function drawChart2D6() { const c = $("chart2"), g = c.getContext("2d"), w = c.clientWidth, h = c.clientHeight; if (!w) return; if (c.width !== w) { c.width = w; c.height = h; }
  const R_ = H.diag.rec, n = R_.length, X = (i) => i / (n - 1) * w, h1 = Math.round(h * 0.34), h2 = Math.round(h * 0.33), y3 = h1 + h2, h3 = h - y3; g.clearRect(0, 0, w, h); g.fillStyle = "#0d0f12"; g.fillRect(0, 0, w, h);
  g.font = "10px ui-monospace, Menlo"; const node = d6Node(H.testD), s = node && node.forceSeries;
  if (s) { const fmax = Math.max(500, ...s.F.map(f => f ? Math.hypot(f[0], f[2]) : 0)), idx = (i) => Math.round((R_[i].t - s.t0) / s.dt);
    for (const [key, col] of [["turf", "#50d070"], ["F", "#ff5050"]]) { g.strokeStyle = col; g.beginPath(); for (let i = 0; i < n; i++) { const k = idx(i), v = k >= 0 && k < s[key].length && s[key][k] ? Math.hypot(s[key][k][0], s[key][k][2]) : 0, y = h1 - 1 - Math.min(1, v / fmax) * (h1 - 12); i ? g.lineTo(X(i), y) : g.moveTo(X(i), y); } g.stroke(); }
    g.fillStyle = "#9aa0a6"; g.fillText(`contact force A→B (red) · turf→B (green), horizontal — instrumented twin, exact · max ${fmax.toFixed(0)} N`, 6, 10); }
  else { g.fillStyle = "#9aa0a6"; g.fillText("contact force: no Node matrix entry for this test (run tools/d6x_run.js)", 6, 10); }
  const lmax = Math.max(800, ...R_.map(q => Math.max(q.B.feet.L.load, q.B.feet.R.load)));
  for (let i = 0; i < n; i++) { const q = R_[i].B.feet; if (q.L.slip) { g.fillStyle = "#ff303033"; g.fillRect(X(i), h1, Math.max(1, w / n), h2); } if (!q.R.touch) { g.fillStyle = "#3080ff33"; g.fillRect(X(i), h1, Math.max(1, w / n), h2); } }
  for (const [side, col] of [["L", "#ffa040"], ["R", "#40c8ff"]]) { g.strokeStyle = col; g.beginPath(); for (let i = 0; i < n; i++) { const y = h1 + h2 - 1 - Math.max(0, R_[i].B.feet[side].load) / lmax * (h2 - 12); i ? g.lineTo(X(i), y) : g.moveTo(X(i), y); } g.stroke(); }
  g.fillStyle = "#9aa0a6"; g.fillText(`foot load: struck L (orange) · far R (cyan), max ${lmax.toFixed(0)} N · red = struck foot SLIPPING · blue = far foot off the turf`, 6, h1 + 10);
  const xm = (v) => y3 + 4 + (0.2 - Math.max(-0.3, Math.min(0.2, v))) / 0.5 * (h3 - 12); g.strokeStyle = "#555"; g.beginPath(); g.moveTo(0, xm(0)); g.lineTo(w, xm(0)); g.stroke();
  g.strokeStyle = "#e0e0e0"; g.beginPath(); for (let i = 0; i < n; i++) { const v = R_[i].B.xiM, y = xm(v <= -999 ? -0.3 : v); i ? g.lineTo(X(i), y) : g.moveTo(X(i), y); } g.stroke();
  for (let i = 0; i < n; i++) { g.fillStyle = CLS_COL[R_[i].B.cls] || "#888"; g.fillRect(X(i), h - 5, Math.max(1, w / n), 5); if (R_[i].B.stage && !["STAND", "IDLE"].includes(R_[i].B.stage)) { g.fillStyle = "#b080ff"; g.fillRect(X(i), h - 9, Math.max(1, w / n), 3); } }
  g.fillStyle = "#9aa0a6"; g.fillText("B capture-point margin ξ (white; 0 = support edge, −30 cm clipped) · classification band (bottom) · stepping (violet)", 6, y3 + 10);
  g.fillStyle = "#fff"; g.fillRect(X(H.i) - 1, 0, 2, h); }
const f1 = (x, d = 1) => x == null || !Number.isFinite(+x) ? "-" : (+x).toFixed(d);
function cursorD6() { const el = $("d6cur"); if (!el || !H.diag) return; const d = H.diag.rec[H.i]; if (!d) return; const b = d.B, J_ = b.joints, fz = d6Force(d.t);
  const jr = (n, lab, ax) => { const j = J_[n]; if (!j) return ""; const one = !Array.isArray(j.a), a = one ? j.a : j.a[ax], tq = one ? j.tq : j.tq[ax], sp = one ? j.spr : j.spr[ax], dm = one ? j.dmp : j.dmp[ax];
    return `<tr><td>${lab}</td><td>${f1(a)}°</td><td>${f1(tq, 0)}</td><td class="${j.sat >= 0.98 ? "bad" : ""}">${f1(j.sat * 100, 0)} %</td><td>${f1(sp, 0)} / ${f1(dm, 0)}</td></tr>`; };
  el.innerHTML = `t ${d.t.toFixed(3)} s · B <b style="color:${CLS_COL[b.cls] || "#fff"}">${b.cls}</b>${b.frozen ? " (FROZEN — diagnostic)" : ""}${b.stage && b.stage !== "STAND" ? " · C3 " + b.stage : ""}${b.refused ? " · C3 refused: " + b.refused : ""}<br>`
    + `contact ${d.pairs.length ? d.pairs.map(p => `${p.a}→${p.b} @${p.y.toFixed(2)} m`).join(", ") : d.spec ? "speculative only" : "none"}${fz && fz.F ? ` · A→B ${Math.hypot(fz.F[0], fz.F[2]).toFixed(0)} N, turf→B ${fz.turf ? Math.hypot(fz.turf[0], fz.turf[2]).toFixed(0) : "-"} N (twin)` : ""}<br>`
    + `struck L ${b.feet.L.st} ${b.feet.L.load} N${b.feet.L.slip ? " SLIP" : ""} · far R ${b.feet.R.st} ${b.feet.R.load} N · ξ margin ${b.xiM > -999 ? f1(b.xiM * 100) + " cm" : "no support"} · COM ${f1(Math.hypot(b.vcom[0], b.vcom[2]), 2)} m/s · trunk ${f1(b.trunk)}°`
    + `<table><tr><th>struck leg</th><th>angle</th><th>τ N·m</th><th>sat</th><th>spring / damping N·m</th></tr>${jr("ankle_L", "ankle roll (Z)", 2)}${jr("knee_L", "knee flexion", 0)}${jr("hip_L", "hip ad/abduction (Z)", 2)}${jr("hip_L", "hip flex/ext (Y)", 1)}${jr("hip_R", "far hip ad/abd (Z)", 2)}</table>`; }
function renderSideD6() { const S = H.diagSum, n = d6Node(H.testD), row = (k, v, bad) => `<tr><td>${k}</td><td class="${bad ? "bad" : ""}">${v}</td></tr>`;
  let h = `<h3>D6 diagnostic — ${H.testD}</h3><div class="small">${TD(H.testD).title}. Everything below is MEASURED from the solved bodies (pc_d6diag); the response label is a description of those measurements, never an input.</div>`;
  h += `<div style="display:flex;flex-wrap:wrap;gap:4px;margin:6px 0">${D6X_COMPARE.map(([k, lab]) => `<button onclick="D6_PICK('${k}')" style="background:${k === H.testD ? "#f0c060" : "#262a30"};color:${k === H.testD ? "#111" : "#e6e4df"};border:1px solid #2e3238;border-radius:4px;padding:2px 6px;font:11px -apple-system,system-ui;cursor:pointer">${lab}</button>`).join("")}</div><table>`;
  if (!S) return h + "</table>";
  const C = S.contact, M = n && n.momentum, Fe = S.feet, Bo = S.body;
  h += row("observed response", `<b>${S.outcome}</b>${n && n.twin && n.twin.outcome !== S.outcome ? `<br><span class=small>instrumented twin (Node): ${n.twin.outcome} — this case sits on a decision boundary</span>` : ""}`, /fall/.test(S.outcome));
  h += row("1 · contact", C.pair ? `${C.pair} at ${f1(C.heightM, 2)} m (${C.where}) · slider ${f1(C.aSpeed, 2)} m/s at touch · first touch ${f1(C.firstTouchT, 3)} s · bodies hit: ${C.bodiesHit.join(", ")} · deepest ${f1(C.maxDepthMm)} mm` : "none");
  if (M) { const Wn = M.windows, wr = (k) => `<tr><td>${k}</td><td>${f1(Wn[k].AtoB[0])}</td><td>${f1(Wn[k].AtoB[2])}</td><td>${f1(Wn[k].turfToB[0])}</td><td>${f1(Wn[k].turfToB[1])}</td></tr>`;
    h += row("2 · contact impulse (twin, exact)", `peak ${M.peakForceN} N at +${M.peakAtMs} ms · high force (> 25 % of peak) for ${M.highForceMs ?? "-"} ms<br><table class=small><tr><th>window</th><th>A→B x</th><th>A→B z</th><th>turf→B x</th><th>turf→B y</th></tr>${Object.keys(Wn).map(wr).join("")}</table>`);
    h += row("momentum transfer", `slider ${M.A.atTouch} N·s at touch → ${M.A.after100} (+100 ms) → ${M.A.after250} (+250 ms) → ${M.A.after500} (+500 ms) · B's whole-body peak ${M.BpeakMomentum} N·s (COM ${f1(M.BpeakComSpeed, 2)} m/s): B's feet hand the rest to the turf`); }
  h += row("3 · struck foot", `slid ${f1(Fe.struckSlideCm)} cm (peak ${f1(Fe.struckPeakSpeed, 2)} m/s, SLIPPING ${Fe.struckSlipMs} ms, off the turf ${Fe.struckAirMs} ms) · peak load ${Fe.struckPeakLoadN} N (before: L ${Fe.preLoad.L} / R ${Fe.preLoad.R} N) · far foot off the turf ${Fe.farAirMs} ms, moved ${f1(Fe.farMovedCm)} cm`);
  h += row("4 · joints (first 150 ms)", `<table class=small><tr><th>joint</th><th>excursion °</th><th>peak rate °/s</th><th>peak τ N·m</th><th>sat steps</th><th>spring / damping N·m</th></tr>${Object.entries(S.joints).map(([k, j]) => `<tr><td>${k} ${j.axes.join("/")}</td><td>${j.excursionDeg.join(" / ")}</td><td>${j.peakRateDegS.join(" / ")}</td><td>${j.peakTorqueNm.join(" / ")}</td><td>${j.satSteps}</td><td>${j.peakSpringNm.join(" / ")} · ${j.peakDampingNm.join(" / ")}</td></tr>`).join("")}</table>`);
  h += row("5 · whole body", `COM peak ${f1(Bo.comPeakSpeed, 2)} m/s at ${f1(Bo.comPeakT, 3)} s · moved ${f1(Bo.comMovedCm)} cm · dropped ${f1(Bo.comDropCm)} cm · trunk ≤ ${f1(Bo.trunkMaxDeg)}° · |L| horizontal ≤ ${f1(Bo.Lpeak)} kg·m²/s · ξ min ${f1(Bo.xiMinCm)} cm (outside ${Bo.xiOutsideMs} ms${Bo.noSupportMs ? `, no support polygon ${Bo.noSupportMs} ms` : ""})`, /fall/.test(S.outcome));
  h += row("6 · classification", S.classes.map(c => `<span style="color:${CLS_COL[c.state] || "#fff"}">${f1(c.t, 3)} ${c.state}</span>${c.why ? ` <span class=small>(${c.why})</span>` : ""}`).join("<br>"));
  h += row("7 · C3 stepping", (S.stepper.length ? S.stepper.map(e => `${f1(e.t, 3)} ${e.kind}: ${e.what}`).join("<br>") : "no step decision") + (S.refused ? `<br><span class=small>refused: ${S.refused}</span>` : ""));
  h += `</table><h3>at the cursor</h3><div id="d6cur" class="small"></div>`;
  if (H.d6x) h += `<h3>D6 diagnostic matrix (Node ×3, deterministic; twin = instrumented run)</h3><table class=small><tr><th>test</th><th>response</th><th>arrive m/s</th><th>contact</th><th>A→B 35 ms / total N·s</th><th>foot cm</th><th>COM m/s</th><th>twin</th></tr>` + H.d6x.results.map(q => { const m = q.momentum;
      return `<tr style="cursor:pointer;${q.test === H.testD ? "background:#3a3320" : ""}" onclick="D6_PICK('${q.test}')"><td>${q.test}</td><td class="${/fall/.test(q.outcome) ? "bad" : /step/.test(q.outcome) ? "" : "ok"}">${q.outcome}</td><td>${f1(q.contact.aSpeed, 1)}</td><td>${q.contact.pair ? q.contact.pair.replace("foot_R → ", "") + " @" + f1(q.contact.heightM, 2) : "-"}</td><td>${m ? f1(m.windows["−10–35 ms"].AtoB[0], 0) + " / " + f1(Object.values(m.windows).reduce((s, w) => s + w.AtoB[0], 0), 0) : "-"}</td><td>${f1(q.feet.struckSlideCm, 0)}</td><td>${f1(q.body.comPeakSpeed, 2)}</td><td class=small>${q.twin.outcome === q.outcome ? "=" : q.twin.outcome}</td></tr>`; }).join("") + `</table>`;
  return h; }
