// generic-swing trace: commanded vs actual foot (forward rel. landing, height, pitch), the actual lowest outline corner, contact / load
import { J, body, G2, M } from "../fg/lib.mjs"; const { Q, V } = M;
const first = process.argv[2] || "R", at = +(process.argv[3] || 0.6), K = +(process.argv[4] || 1), HX = JSON.parse(process.argv[5] || '{"swingGen":"v2"}'), { spec, poses } = body(process.argv[6] || "F0"), bi = (n) => spec.bodies.findIndex(b => b.name === n);
const steps = Array.from({ length: 30 }, (_, i) => ({ sw: (i % 2 === 0) === (first === "R") ? "R" : "L", ...(i === 0 ? { fwdK: 0.7 } : i === 1 ? { fwdK: 0.9 } : {}) }));
let LOCO = null; const T = []; const r = G2.runG2a(J, spec, "G2W_A8", { poses, keepStates: true, seconds: 1.6 + 30 * 0.58, rhythmOver: { steps, at, ...(process.env.OPEN ? { walk: { char: Object.fromEntries([[0, { df: 0.224, dl: 0.343, T: 0.469 }], ...Array.from({ length: 11 }, (_, i) => [i + 1, { df: 0.28, dl: 0.26, T: 0.42 }])]) } } : {}) }, humanOver: HX, ...(process.env.LOCO ? { locoOver: JSON.parse(process.env.LOCO) } : {}), onLoco: (l) => { LOCO = l; const f = l.planner.exec.refSwing; l.planner.exec.refSwing = (R, t, o, nv) => { const out = f(R, t, o, nv); if (!nv) T.push({ t, k: R.stepIndex, pos: out.pos, rot: out.rot, reach: out.reach, u: out.u, ph: out.sw2, rho: out.rho }); return out; }; } });
const P = LOCO.planner, h0 = P.rhythm.wk.h0, hd = [Math.sin(h0), 0, Math.cos(h0)], d = P.exec.done.find(d => d.stepIndex === K), fb = bi("foot_" + d.sw), box = spec.bodies[fb].planBox || spec.bodies[fb].shapes[0];
const low = (S) => Math.min(...[-1, 1].flatMap(sx => [-1, 1].map(sz => S.pos[1] + Q.rot(S.rot, [box.pos[0] + sx * box.he[0], box.pos[1] - box.he[1], box.pos[2] + sz * box.he[2]])[1]))), pit = (q) => { const f = Q.rot(q, [0, 0, 1]); return Math.atan2(f[1], Math.hypot(f[0], f[2])) * 57.3; };
const last = T.filter(e => e.k === K).pop(), land = last.reach, fw = (p) => (p[0] - land[0]) * hd[0] + (p[2] - land[2]) * hd[2];
console.log("hash", r.hash, "step", K, d.sw, d.status, "lift", d.liftoff && (d.liftoff.t - d.tSw0).toFixed(3), "td", d.td && (d.td.t - d.tSw0).toFixed(3), "uAt", d.td && d.td.uAt.toFixed(2), "R.sw2", JSON.stringify(d.sw2 && d.sw2.info));
console.log(" t     ph   u   | fwd cmd  act | y cmd  act | pitch cmd act | lowest act | touch load");
for (const q of r.recs.filter(q => q.t >= d.tSw0 - 0.01 && q.t <= (d.td ? d.td.t : d.tSw0 + 0.5) + 0.03 && q.n % 4 === 0)) { const c = T.filter(e => e.k === K && e.t <= q.t + 1e-9).pop(); if (!c) continue; const S = q.states[fb];
  console.log(`${(q.t - d.tSw0).toFixed(3)} ${String(c.ph).padEnd(4)} ${c.u.toFixed(2)} | ${(fw(c.pos) * 100).toFixed(1).padStart(6)} ${(fw(S.pos) * 100).toFixed(1).padStart(6)} | ${(c.pos[1] * 100).toFixed(1).padStart(5)} ${(S.pos[1] * 100).toFixed(1).padStart(5)} | ${(c.rho * 57.3).toFixed(0).padStart(4)} ${pit(S.rot).toFixed(0).padStart(4)} | ${(low(S) * 100).toFixed(1).padStart(5)} | ${q.feet[d.sw].touching ? "T" : "-"} ${(q.feet[d.sw].load / 765).toFixed(2)}`); }
