// swing hip / knee: PD hold vs damping vs ID feed-forward vs gravity terms, flexion axis, over one swing (old and new generator)
import { J, body, G2 } from "../fg/lib.mjs";
const first = process.env.FIRST || "R", at = +(process.env.AT || 0.6), K = +(process.argv[2] || 1), HX = JSON.parse(process.argv[3] || "{}"), { spec, poses } = body("F0");
const steps = Array.from({ length: 30 }, (_, i) => ({ sw: (i % 2 === 0) === (first === "R") ? "R" : "L", ...(i === 0 ? { fwdK: 0.7 } : i === 1 ? { fwdK: 0.9 } : {}) }));
let LOCO = null; const r = G2.runG2a(J, spec, "G2W_A8", { poses, keepStates: true, seconds: 1.6 + 30 * 0.58, rhythmOver: { steps, at, ...(process.env.OPEN ? { walk: { char: Object.fromEntries([[0, { df: 0.224, dl: 0.343, T: 0.469 }], ...Array.from({ length: 11 }, (_, i) => [i + 1, { df: 0.28, dl: 0.26, T: 0.42 }])]) } } : {}) }, humanOver: HX, onLoco: (l) => { LOCO = l; } });
const d = LOCO.planner.exec.done.find(d => d.stepIndex === K), s = d.sw, ji = (n) => spec.joints.findIndex(j => j.name === n), ax = (v, i) => Array.isArray(v) ? v[i] : (i === 0 ? v : 0);
console.log("step", K, s, "lift", (d.liftoff.t - d.tSw0).toFixed(3), "td", (d.td.t - d.tSw0).toFixed(3), "| hip axis 1: hold damp grav ID real sat | knee: hold damp grav ID real");
for (const q of r.recs.filter(q => q.t >= d.tSw0 && q.t <= d.td.t && q.n % 6 === 0)) { const H = q.arb[ji("hip_" + s)], env = H.env, Kn = q.arb[ji("knee_" + s)], tm = (e, m, i) => { const x = e.terms.find(z => z.m === m); return x ? ax(x.alw !== undefined ? x.alw : x.req, i) : 0; };
  const f = (v) => v.toFixed(0).padStart(5); console.log(`${(q.t - d.tSw0).toFixed(3)} | ${f(tm(H, "swing", 1))}${f(tm(H, "damping", 1))}${f(tm(H, "gravity", 1))}${f(tm(H, "swing ID feed-forward", 1))}${f(ax(H.real, 1))} ${Array.isArray(H.sat) && H.sat[1] ? "S" : " "} env[${env ? env.lo[1].toFixed(0) + "," + env.hi[1].toFixed(0) : ""}] | ${f(tm(Kn, "swing", 0))}${f(tm(Kn, "damping", 0))}${f(tm(Kn, "gravity", 0))}${f(tm(Kn, "swing ID feed-forward", 0))}${f(ax(Kn.real, 0))}`); }
