import { J, body, G2, M } from "../fg/lib.mjs"; import fsM from "fs";
const JDM = "/Users/zainrahman/Downloads/FC Simulator worktrees/physical-character-v1/review_artifacts/physical_character_v1/g2_walker/json/"; const withModels = (c) => c.modelsPrefix ? { ...c, models: Object.fromEntries([0, 0.1, 0.15, 0.2, 0.25].map(t => [t, JSON.parse(fsM.readFileSync(JDM + c.modelsPrefix + t + ".json", "utf8"))])) } : c;
const ctrl = JSON.parse(process.argv[2]), walkX = JSON.parse(process.argv[3] || "{}"), K = +(process.argv[4] || 1);
const { spec, poses } = body("F0"), bi = (n) => spec.bodies.findIndex(b => b.name === n), first = "R", at = 0.5, n = 10, steps = Array.from({ length: n }, (_, i) => ({ sw: (i % 2 === 0) === (first === "R") ? "R" : "L", ...(i === 0 ? { fwdK: 0.7 } : i === 1 ? { fwdK: 0.9 } : {}) }));
let LOCO = null; const base = G2.TESTS_G2W.G2W_A8.loco.rhythm.walk;
const r = G2.runG2a(J, spec, "G2W_A8", { poses, keepStates: true, seconds: 1.6 + n * 0.6, rhythmOver: { steps, at, walk: { ...walkX, ctrl: withModels({ ...base.ctrl, ...ctrl }) } }, onLoco: l => { LOCO = l; } });
const P = LOCO.planner, h0 = P.rhythm.wk.h0, hd = [Math.sin(h0), Math.cos(h0)], d = P.exec.done.find(e => e.stepIndex === K), ps = d.pSt, fw = (a) => (a[0] - ps[0]) * hd[0] + (a[1] - ps[1]) * hd[1];
console.log(`step ${K} ${d.sw}: tSw0 ${d.tSw0.toFixed(3)} liftoff ${d.liftoff.t.toFixed(3)} td ${d.td.t.toFixed(3)}  (stance ${d.st})`);
console.log(" t-tSw0 | ξ_f   c_f   v    | CoP_real cmd | hip−ank  ext  | heel toe touching(st) | stance load");
for (const q of r.recs.filter(q => q.t >= d.tSw0 && q.t <= d.td.t + 0.02 && q.n % 6 === 0)) { const hip = q.states[bi("thigh_" + d.st)].pos, ank = q.states[bi("foot_" + d.st)].pos, ext = Math.hypot(hip[0] - ank[0], hip[1] - ank[1], hip[2] - ank[2]) / 0.9243, F = q.feet[d.st];
  console.log(`${(q.t - d.tSw0).toFixed(3)} | ${fw(q.xi).toFixed(3)} ${fw([q.com[0], q.com[2]]).toFixed(3)} ${(q.vcom[0] * hd[0] + q.vcom[2] * hd[1]).toFixed(2)} | ${q.copSmooth ? fw(q.copSmooth).toFixed(3) : "  -  "} ${q.ctl && q.ctl.pStar ? fw(q.ctl.pStar).toFixed(3) : "  -  "} | ${(fw([hip[0], hip[2]]) - fw([ank[0], ank[2]])).toFixed(3)} ${ext.toFixed(3)} | ${F.heel ? 1 : 0} ${F.toe ? 1 : 0} ${F.touching ? 1 : 0} | ${(F.load / 750).toFixed(2)} ${q.xiRefP ? "ref " + fw(q.xiRefP).toFixed(3) : ""} ${q.vRef ? "vRef " + (q.vRef[0] * hd[0] + q.vRef[1] * hd[1]).toFixed(2) : ""}`); }
