import { J, body, G2, M } from "../fg/lib.mjs"; import fsM from "fs";
const JDM = "/Users/zainrahman/Downloads/FC Simulator worktrees/physical-character-v1/review_artifacts/physical_character_v1/g2_walker/json/"; const withModels = (c) => c.modelsPrefix ? { ...c, models: Object.fromEntries([0, 0.1, 0.15, 0.2, 0.25].map(t => [t, JSON.parse(fsM.readFileSync(JDM + c.modelsPrefix + t + ".json", "utf8"))])) } : c; const { Q } = M;
const ctrl = JSON.parse(process.argv[2]), walkX = JSON.parse(process.argv[3] || "{}"), K0 = +(process.argv[4] || 4), K1 = +(process.argv[5] || 6);
const { spec, poses } = body("F0"), first = "R", at = 0.5, n = 12, steps = Array.from({ length: n }, (_, i) => ({ sw: (i % 2 === 0) === (first === "R") ? "R" : "L", ...(i === 0 ? { fwdK: 0.7 } : i === 1 ? { fwdK: 0.9 } : {}) }));
let LOCO = null; const base = G2.TESTS_G2W.G2W_A8.loco.rhythm.walk;
const r = G2.runG2a(J, spec, "G2W_A8", { poses, keepStates: true, seconds: 1.6 + n * 0.6, rhythmOver: { steps, at, walk: { ...walkX, ctrl: withModels({ ...base.ctrl, ...ctrl }) } }, onLoco: l => { LOCO = l; } });
const P = LOCO.planner, h0 = P.rhythm.wk.h0, hd = [Math.sin(h0), Math.cos(h0)], rt = [hd[1], -hd[0]], D = P.exec.done.filter(d => d.kind === "rhythmic");
const yaw = (q) => { const f = Q.rot(q, [0, 0, 1]); return Math.atan2(f[0], f[2]) * 57.3; };
for (const d of D.filter(d => d.stepIndex >= K0 && d.stepIndex <= K1)) { const sd = d.sw === "R" ? 1 : -1, L = (p) => ((p[0] - d.pSt[0]) * rt[0] + (p[1] - d.pSt[1]) * rt[1]) * sd;
  console.log(`step ${d.stepIndex} ${d.sw} (lateral + = toward the swing side) tSw0 ${d.tSw0.toFixed(2)} lift ${d.liftoff ? (d.liftoff.t - d.tSw0).toFixed(2) : "-"} td ${d.td ? (d.td.t - d.tSw0).toFixed(2) : "-"}`);
  for (const q of r.recs.filter(q => q.t >= d.tSw0 && q.t <= (d.td ? d.td.t + 0.12 : d.tSw0 + 0.6) && q.n % 12 === 0)) console.log(`  ${(q.t - d.tSw0).toFixed(2)} ξ_l ${L(q.xi).toFixed(3)} c_l ${L([q.com[0], q.com[2]]).toFixed(3)} v_l ${((q.vcom[0] * rt[0] + q.vcom[2] * rt[1]) * sd).toFixed(2)} | CoP_l real ${q.copSmooth ? L(q.copSmooth).toFixed(3) : "  -  "} cmd ${q.ctl && q.ctl.pStar ? L(q.ctl.pStar).toFixed(3) : "  -  "} ref ${q.xiRefP ? L(q.xiRefP).toFixed(3) : "-"} | yaw ${(yaw(q.states[0].rot)).toFixed(1)} | ${q.feet.L.touching ? "L" : "."}${q.feet.R.touching ? "R" : "."}`); }
