import fs from "fs"; import path from "path";
const PC = process.argv[2], ROOT = path.resolve(PC, "../../..");
const { buildBodySpec } = await import(PC + "/pc_body.js"); const { loadJolt } = await import(PC + "/pc_jolt.js"); const G = await import(PC + "/pc_gateg1a.js"); const { buildPoses } = await import(PC + "/pc_control.js"); const REF = await import(PC + "/pc_ref.js");
REF.initOfLoco(fs.readFileSync(path.join(PC, "../anim3d/of_loco.js"), "utf8"));
const dir = path.join(ROOT, "assets/characters/outfield/gabriel"), rig = JSON.parse(fs.readFileSync(path.join(dir, "rig.json"), "utf8")), buf = fs.readFileSync(path.join(dir, "mesh.bin"));
const ab = buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength), L = rig.mesh.layout, T = { Float32Array, Uint16Array, Uint32Array, Uint8Array };
const mesh = {}; for (const k of ["positions", "joints", "weights", "indices"]) mesh[k] = new T[L[k].elementType](ab, L[k].byteOffset, L[k].elementCount);
const spec = buildBodySpec(rig, mesh, { calib: "V1.1" }), J = await loadJolt(PC + "/vendor/jolt-physics.wasm-compat.js"), poses = buildPoses(spec);
const G2 = await import(PC + "/pc_gateg2.js"); let LOCO = null, done = false;
G2.runG2a(J, spec, "G2b_walk08", { poses, seconds: 2.0, onLoco: (l) => { LOCO = l; const f0 = l.planner.tool._feasible.bind(l.planner.tool); l.planner.tool._feasible = (o, sw, tc, yaw, cur, dCom, T) => { const r = f0(o, sw, tc, yaw, cur, dCom, T); if (!r.ok && o.t > 1.85 && o.t < 1.95) console.log(o.t.toFixed(3), sw, "tc", tc.map(v => v.toFixed(3)).join(","), "dCom", dCom.map(v => v.toFixed(3)).join(","), "→", JSON.stringify(r.reasons || r.why || r)); return r; }; } });
